#------------------------------------------------------------------------------
# Copyright (c) 2000 Extenta, Inc.
#
#------------------------------------------------------------------------------

all : src

.PHONY : src
src :
	cd src && $(MAKE)

.PHONY : clean
clean :
	cd src && $(MAKE) clean

.PHONY : realclean
realclean:
	cd src && $(MAKE) realclean
