#------------------------------------------------------------------------------
# Copyright (c) 2000 Extenta, Inc.
#
#------------------------------------------------------------------------------

PACKAGE = Wml

include $(XTNTAPROJ)/Soft/Generic/$(MAKE_TRGT)/defs.mk

LIBTARGET = $(LIBDIR)/lib$(PACKAGE)$(LIB_DYN_SUFFIX)

.PHONY : all
all : $(LIBTARGET)

.PHONY : clean
clean :
	-@rm -rf $(OBJDIR)/*.o
	-@rm -rf $(LIBTARGET)

include $(XTNTAPROJ)/Soft/Generic/$(MAKE_TRGT)/rules.mk


