/**************************************************
 File: cable_voice.java.
 Desc: Automatic translation of HTML file cable_voice.html.
 Date Translated: Fri Jan 14 09:54:19 2000.
**************************************************/


import wao.server.OutputStream;
import wao.html.*;


public class makeDoc_cable_voice extends HtmlDocCreation {

    static public void main() {
	HtmlDocCreation aTest= new makeDoc_cable_voice();
	OutputStream aStream= new OutputStream();
	aTest.spitDoc(aStream);
    }

    public boolean createIt()
    {
	theDoc= new HtmlDoc("-//W3C//DTD HTML 3.2//EN");
	HHtml html_0= new HHtml();
	html_0.subElements= new HtmlElement[5];
	HComment comment_0= new HComment();
	comment_0.setValue(" Vignette StoryServer 4 Thu Dec 16 10:16:11 1999 --");
	html_0.subElements[0]= comment_0;
	HPcData pcData_0= new HPcData();
	pcData_0.setValue("\r\n\r\n\r\n	\r\n		\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
	html_0.subElements[1]= pcData_0;
	HHead head_0= new HHead();
	head_0.subElements= new HtmlElement[1];
	html_0.subElements[2]= head_0;
	HTitle title_0= new HTitle();
	title_0.subElements= new HtmlElement[1];
	head_0.subElements[0]= title_0;
	HPcData pcData_1= new HPcData();
	pcData_1.setValue("CNET.com - News - Personal Technology - Cable set-top boxes instead of phones?");
	title_0.subElements[0]= pcData_1;
	HPcData pcData_2= new HPcData();
	pcData_2.setValue("\r\n");
	html_0.subElements[3]= pcData_2;
	HBody body_0= new HBody();
	body_0.attributes= new HtmlAttribute[2];
	body_0.attributes[0]= new HtmlAttribute("bgcolor", "\"#ffffff\"");
	body_0.attributes[1]= new HtmlAttribute("text", "\"#000000\"");
	body_0.subElements= new HtmlElement[10];
	html_0.subElements[4]= body_0;
	HPcData pcData_3= new HPcData();
	pcData_3.setValue("\r\n\r\n\r\n\r\n");
	body_0.subElements[0]= pcData_3;
	HScript script_0= new HScript();
	script_0.attributes= new HtmlAttribute[1];
	script_0.attributes[0]= new HtmlAttribute("language", "\"JavaScript\"");
	script_0.subElements= new HtmlElement[3];
	body_0.subElements[1]= script_0;
	HPcData pcData_4= new HPcData();
	pcData_4.setValue("\r\n");
	script_0.subElements[0]= pcData_4;
	HComment comment_1= new HComment();
	comment_1.setValue(" hide from JavaScript-challenged browsers\r\nfunction openWindowDtn(url, name) {\r\n  popupWin = window.open(url, name, 'scrollbars,resizable,width=145,height=450')\r\n}\r\n\r\n\r\nfunction openWindow(url) {\r\n        popUpWin = window.open(url,'graphicWin','toolbar=0,location=no,directories=0,status=0,menubar=1,scrollbars=0,resizable=1,width=330,height=320');\r\n}\r\n\r\nfunction formatString(items) {\r\n         var modplus = \"\";\r\n         for (var t = 1 ; t <= items.length ; t++) {\r\n                if (items.substring(t-1,t) == \" \") {\r\n                    modplus+=\"+\";\r\n                } else {\r\n                    modplus+=items.substring(t-1,t);\r\n                }\r\n        }\r\n        return modplus;\r\n}\r\n\r\nfunction buildUrl() {\r\n        var words;\r\n        words = document.searchform.query.value;\r\n        var searchitems;\r\n        // format words\r\n        searchitems=formatString(words);\r\n        var index;  \r\n        index = document.searchform.usesite.selectedIndex;\r\n        var site;\r\n        site = document.searchform.usesite.options[index].value;\r\n        site+=searchitems;\r\n        // execute\r\n        location.href = site;\r\n}\r\n\r\nfunction openWindowDtn(url, name) {\r\n  popupWin = window.open(url, name, 'scrollbars,resizable,width=145,height=450')\r\n}\r\n\r\nfunction openWin(url, name) {\r\n             popupWin = null;\r\n             popupWin=window.open(url,name,'resizable=yes,scrollbars=yes,width=520,height=265');\r\n            \r\n             // focus window (only for Navigator 3.0)\r\n             if ( (navigator.appName != \"Microsoft Internet Explorer\") && (navigator.appVersion.substring(0,1) == \"3\") )\r\n             popupWin.focus();\r\n     }\r\n\r\n//--");
	script_0.subElements[1]= comment_1;
	HPcData pcData_5= new HPcData();
	pcData_5.setValue(" \r\n");
	script_0.subElements[2]= pcData_5;
	HPcData pcData_6= new HPcData();
	pcData_6.setValue("\r\n\r\n\r\n");
	body_0.subElements[2]= pcData_6;
	HComment comment_2= new HComment();
	comment_2.setValue(" Vignette StoryServer 4 Wed Dec 15 18:49:50 1999 --");
	body_0.subElements[3]= comment_2;
	HPcData pcData_7= new HPcData();
	pcData_7.setValue("\r\n\r\n		");
	body_0.subElements[4]= pcData_7;
	HTable table_0= new HTable();
	table_0.attributes= new HtmlAttribute[5];
	table_0.attributes[0]= new HtmlAttribute("width", "\"100%\"");
	table_0.attributes[1]= new HtmlAttribute("border", "0");
	table_0.attributes[2]= new HtmlAttribute("cellspacing", "0");
	table_0.attributes[3]= new HtmlAttribute("cellpadding", "0");
	table_0.attributes[4]= new HtmlAttribute("bgcolor", "\"#000000\"");
	table_0.subElements= new HtmlElement[1];
	body_0.subElements[5]= table_0;
	HTableRow tableRow_0= new HTableRow();
	tableRow_0.subElements= new HtmlElement[2];
	table_0.subElements[0]= tableRow_0;
	HTableData tableData_0= new HTableData();
	tableData_0.attributes= new HtmlAttribute[2];
	tableData_0.attributes[0]= new HtmlAttribute("height", "25");
	tableData_0.attributes[1]= new HtmlAttribute("align", "left");
	tableData_0.subElements= new HtmlElement[2];
	tableRow_0.subElements[0]= tableData_0;
	HPcData pcData_8= new HPcData();
	pcData_8.setValue("\r\n		");
	tableData_0.subElements[0]= pcData_8;
	HFont font_0= new HFont();
	font_0.attributes= new HtmlAttribute[3];
	font_0.attributes[0]= new HtmlAttribute("face", "\"MS Sans Serif, Geneva, Helvetica\"");
	font_0.attributes[1]= new HtmlAttribute("size", "\"-2\"");
	font_0.attributes[2]= new HtmlAttribute("color", "\"#FFCC00\"");
	font_0.subElements= new HtmlElement[22];
	tableData_0.subElements[1]= font_0;
	HPcData pcData_9= new HPcData();
	pcData_9.setValue(" ");
	font_0.subElements[0]= pcData_9;
	HPcData pcData_10= new HPcData();
	pcData_10.setValue(" ");
	font_0.subElements[1]= pcData_10;
	HAnchor anchor_0= new HAnchor();
	anchor_0.attributes= new HtmlAttribute[1];
	anchor_0.attributes[0]= new HtmlAttribute("href", "\"/frontdoor/0-1.html?tag=stsb.1\"");
	anchor_0.subElements= new HtmlElement[1];
	font_0.subElements[2]= anchor_0;
	HFont font_1= new HFont();
	font_1.attributes= new HtmlAttribute[1];
	font_1.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_1.subElements= new HtmlElement[1];
	anchor_0.subElements[0]= font_1;
	HBold bold_0= new HBold();
	bold_0.subElements= new HtmlElement[1];
	font_1.subElements[0]= bold_0;
	HPcData pcData_11= new HPcData();
	pcData_11.setValue("CNET");
	bold_0.subElements[0]= pcData_11;
	HPcData pcData_12= new HPcData();
	pcData_12.setValue("\r\n			|\r\n		");
	font_0.subElements[3]= pcData_12;
	HAnchor anchor_1= new HAnchor();
	anchor_1.attributes= new HtmlAttribute[1];
	anchor_1.attributes[0]= new HtmlAttribute("href", "\"/news/0-1002.html?tag=st.cn.1006-ron.sb.1002\"");
	anchor_1.subElements= new HtmlElement[1];
	font_0.subElements[4]= anchor_1;
	HFont font_2= new HFont();
	font_2.attributes= new HtmlAttribute[1];
	font_2.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_2.subElements= new HtmlElement[1];
	anchor_1.subElements[0]= font_2;
	HBold bold_1= new HBold();
	bold_1.subElements= new HtmlElement[1];
	font_2.subElements[0]= bold_1;
	HPcData pcData_13= new HPcData();
	pcData_13.setValue("News");
	bold_1.subElements[0]= pcData_13;
	HPcData pcData_14= new HPcData();
	pcData_14.setValue("\r\n			|\r\n		");
	font_0.subElements[5]= pcData_14;
	HAnchor anchor_2= new HAnchor();
	anchor_2.attributes= new HtmlAttribute[1];
	anchor_2.attributes[0]= new HtmlAttribute("href", "\"/hardware/0-1016.html?tag=st.cn.1006-ron.sb.1016\"");
	anchor_2.subElements= new HtmlElement[1];
	font_0.subElements[6]= anchor_2;
	HFont font_3= new HFont();
	font_3.attributes= new HtmlAttribute[1];
	font_3.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_3.subElements= new HtmlElement[1];
	anchor_2.subElements[0]= font_3;
	HBold bold_2= new HBold();
	bold_2.subElements= new HtmlElement[1];
	font_3.subElements[0]= bold_2;
	HPcData pcData_15= new HPcData();
	pcData_15.setValue("Hardware");
	bold_2.subElements[0]= pcData_15;
	HPcData pcData_16= new HPcData();
	pcData_16.setValue("\r\n			|\r\n		");
	font_0.subElements[7]= pcData_16;
	HAnchor anchor_3= new HAnchor();
	anchor_3.attributes= new HtmlAttribute[1];
	anchor_3.attributes[0]= new HtmlAttribute("href", "\"/downloads?tag=st.cn.1006-ron.sb.cn\"");
	anchor_3.subElements= new HtmlElement[1];
	font_0.subElements[8]= anchor_3;
	HFont font_4= new HFont();
	font_4.attributes= new HtmlAttribute[1];
	font_4.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_4.subElements= new HtmlElement[1];
	anchor_3.subElements[0]= font_4;
	HBold bold_3= new HBold();
	bold_3.subElements= new HtmlElement[1];
	font_4.subElements[0]= bold_3;
	HPcData pcData_17= new HPcData();
	pcData_17.setValue("Downloads");
	bold_3.subElements[0]= pcData_17;
	HPcData pcData_18= new HPcData();
	pcData_18.setValue("\r\n			|\r\n		");
	font_0.subElements[9]= pcData_18;
	HAnchor anchor_4= new HAnchor();
	anchor_4.attributes= new HtmlAttribute[1];
	anchor_4.attributes[0]= new HtmlAttribute("href", "\"/specialreports/0-6014.html?tag=st.cn.1006-ron.sb.6014\"");
	anchor_4.subElements= new HtmlElement[1];
	font_0.subElements[10]= anchor_4;
	HFont font_5= new HFont();
	font_5.attributes= new HtmlAttribute[1];
	font_5.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_5.subElements= new HtmlElement[1];
	anchor_4.subElements[0]= font_5;
	HBold bold_4= new HBold();
	bold_4.subElements= new HtmlElement[1];
	font_5.subElements[0]= bold_4;
	HPcData pcData_19= new HPcData();
	pcData_19.setValue("Trends");
	bold_4.subElements[0]= pcData_19;
	HPcData pcData_20= new HPcData();
	pcData_20.setValue("\r\n			|\r\n		");
	font_0.subElements[11]= pcData_20;
	HAnchor anchor_5= new HAnchor();
	anchor_5.attributes= new HtmlAttribute[1];
	anchor_5.attributes[0]= new HtmlAttribute("href", "\"http://www.gamecenter.com/?tag=st.cn.1006-ron.sb.gc\"");
	anchor_5.subElements= new HtmlElement[1];
	font_0.subElements[12]= anchor_5;
	HFont font_6= new HFont();
	font_6.attributes= new HtmlAttribute[1];
	font_6.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_6.subElements= new HtmlElement[1];
	anchor_5.subElements[0]= font_6;
	HBold bold_5= new HBold();
	bold_5.subElements= new HtmlElement[1];
	font_6.subElements[0]= bold_5;
	HPcData pcData_21= new HPcData();
	pcData_21.setValue("Games");
	bold_5.subElements[0]= pcData_21;
	HPcData pcData_22= new HPcData();
	pcData_22.setValue("\r\n			|\r\n		");
	font_0.subElements[13]= pcData_22;
	HAnchor anchor_6= new HAnchor();
	anchor_6.attributes= new HtmlAttribute[1];
	anchor_6.attributes[0]= new HtmlAttribute("href", "\"/techjobs/0-7067.html?tag=st.cn.1006-ron.sb.7067\"");
	anchor_6.subElements= new HtmlElement[1];
	font_0.subElements[14]= anchor_6;
	HFont font_7= new HFont();
	font_7.attributes= new HtmlAttribute[1];
	font_7.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_7.subElements= new HtmlElement[1];
	anchor_6.subElements[0]= font_7;
	HBold bold_6= new HBold();
	bold_6.subElements= new HtmlElement[1];
	font_7.subElements[0]= bold_6;
	HPcData pcData_23= new HPcData();
	pcData_23.setValue("Jobs");
	bold_6.subElements[0]= pcData_23;
	HPcData pcData_24= new HPcData();
	pcData_24.setValue("\r\n			|\r\n		");
	font_0.subElements[15]= pcData_24;
	HAnchor anchor_7= new HAnchor();
	anchor_7.attributes= new HtmlAttribute[3];
	anchor_7.attributes[0]= new HtmlAttribute("href", "\"/exredirect/template/1,10048,,00.html?tag=ex.cn.1006-ron.sb.au&destURL=http%3A%2F%2Fauctions%2Ecnet%2Ecom%2F\"");
	anchor_7.attributes[1]= new HtmlAttribute("onmouseover", "\"status='http://auctions.cnet.com/'; return true;\"");
	anchor_7.attributes[2]= new HtmlAttribute("onmouseout", "\"status=''\"");
	anchor_7.subElements= new HtmlElement[1];
	font_0.subElements[16]= anchor_7;
	HFont font_8= new HFont();
	font_8.attributes= new HtmlAttribute[1];
	font_8.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_8.subElements= new HtmlElement[1];
	anchor_7.subElements[0]= font_8;
	HBold bold_7= new HBold();
	bold_7.subElements= new HtmlElement[1];
	font_8.subElements[0]= bold_7;
	HPcData pcData_25= new HPcData();
	pcData_25.setValue("Auctions");
	bold_7.subElements[0]= pcData_25;
	HPcData pcData_26= new HPcData();
	pcData_26.setValue("\r\n			|\r\n		");
	font_0.subElements[17]= pcData_26;
	HAnchor anchor_8= new HAnchor();
	anchor_8.attributes= new HtmlAttribute[1];
	anchor_8.attributes[0]= new HtmlAttribute("href", "\"/shopping/0-1257.html?tag=st.cn.1006-ron.sb.1257\"");
	anchor_8.subElements= new HtmlElement[1];
	font_0.subElements[18]= anchor_8;
	HFont font_9= new HFont();
	font_9.attributes= new HtmlAttribute[1];
	font_9.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_9.subElements= new HtmlElement[1];
	anchor_8.subElements[0]= font_9;
	HBold bold_8= new HBold();
	bold_8.subElements= new HtmlElement[1];
	font_9.subElements[0]= bold_8;
	HPcData pcData_27= new HPcData();
	pcData_27.setValue("Prices");
	bold_8.subElements[0]= pcData_27;
	HPcData pcData_28= new HPcData();
	pcData_28.setValue("\r\n			|\r\n		");
	font_0.subElements[19]= pcData_28;
	HAnchor anchor_9= new HAnchor();
	anchor_9.attributes= new HtmlAttribute[3];
	anchor_9.attributes[0]= new HtmlAttribute("href", "\"/exredirect/template/1,10048,,00.html?tag=ex.cn.1006-ron.sb.hp&destURL=http%3A%2F%2Fwww%2Ehelp%2Ecom%2F\"");
	anchor_9.attributes[1]= new HtmlAttribute("onmouseover", "\"status='http://www.help.com/'; return true;\"");
	anchor_9.attributes[2]= new HtmlAttribute("onmouseout", "\"status=''\"");
	anchor_9.subElements= new HtmlElement[1];
	font_0.subElements[20]= anchor_9;
	HFont font_10= new HFont();
	font_10.attributes= new HtmlAttribute[1];
	font_10.attributes[0]= new HtmlAttribute("color", "'#FFCC00'");
	font_10.subElements= new HtmlElement[1];
	anchor_9.subElements[0]= font_10;
	HBold bold_9= new HBold();
	bold_9.subElements= new HtmlElement[1];
	font_10.subElements[0]= bold_9;
	HPcData pcData_29= new HPcData();
	pcData_29.setValue("Tech Help");
	bold_9.subElements[0]= pcData_29;
	HPcData pcData_30= new HPcData();
	pcData_30.setValue("\r\n		");
	font_0.subElements[21]= pcData_30;
	HTableData tableData_1= new HTableData();
	tableData_1.attributes= new HtmlAttribute[1];
	tableData_1.attributes[0]= new HtmlAttribute("align", "right");
	tableData_1.subElements= new HtmlElement[3];
	tableRow_0.subElements[1]= tableData_1;
	HPcData pcData_31= new HPcData();
	pcData_31.setValue("\r\n");
	tableData_1.subElements[0]= pcData_31;
	HAnchor anchor_10= new HAnchor();
	anchor_10.attributes= new HtmlAttribute[3];
	anchor_10.attributes[0]= new HtmlAttribute("href", "\"/go/to?tag=ex.cn.1.sb.email&destURL=http://www.email.com/%3Fsr=st.cn.sb\"");
	anchor_10.attributes[1]= new HtmlAttribute("onmouseover", "\"status='http://www.email.com/'; return true;\"");
	anchor_10.attributes[2]= new HtmlAttribute("onmouseout", "\"status=''\"");
	anchor_10.subElements= new HtmlElement[1];
	tableData_1.subElements[1]= anchor_10;
	HFont font_11= new HFont();
	font_11.attributes= new HtmlAttribute[3];
	font_11.attributes[0]= new HtmlAttribute("face", "\"MS Sans Serif, Geneva, Helvetica\"");
	font_11.attributes[1]= new HtmlAttribute("size", "\"-2\"");
	font_11.attributes[2]= new HtmlAttribute("color", "\"#FFCC00\"");
	font_11.subElements= new HtmlElement[1];
	anchor_10.subElements[0]= font_11;
	HBold bold_10= new HBold();
	bold_10.subElements= new HtmlElement[1];
	font_11.subElements[0]= bold_10;
	HPcData pcData_32= new HPcData();
	pcData_32.setValue("Free Email");
	bold_10.subElements[0]= pcData_32;
	HFont font_12= new HFont();
	font_12.attributes= new HtmlAttribute[2];
	font_12.attributes[0]= new HtmlAttribute("face", "\"MS Sans Serif, Geneva, Helvetica\"");
	font_12.attributes[1]= new HtmlAttribute("size", "\"-2\"");
	tableData_1.subElements[2]= font_12;
	HPcData pcData_33= new HPcData();
	pcData_33.setValue("\r\n	\r\n			");
	body_0.subElements[6]= pcData_33;
	HMap map_0= new HMap();
	map_0.attributes= new HtmlAttribute[1];
	map_0.attributes[0]= new HtmlAttribute("name", "\"redball\"");
	map_0.subElements= new HtmlElement[2];
	body_0.subElements[7]= map_0;
	HArea area_0= new HArea();
	area_0.attributes= new HtmlAttribute[3];
	area_0.attributes[0]= new HtmlAttribute("shape", "\"circle\"");
	area_0.attributes[1]= new HtmlAttribute("coords", "\"28, 27, 25\"");
	area_0.attributes[2]= new HtmlAttribute("href", "\"/frontdoor/0-1.html?st.1006.1006-ron.yhed.1\"");
	map_0.subElements[0]= area_0;
	HArea area_1= new HArea();
	area_1.attributes= new HtmlAttribute[1];
	area_1.attributes[0]= new HtmlAttribute("shape", "\"default\"");
	map_0.subElements[1]= area_1;
	HPcData pcData_34= new HPcData();
	pcData_34.setValue("\r\n\r\n			");
	body_0.subElements[8]= pcData_34;
	HTable table_1= new HTable();
	table_1.attributes= new HtmlAttribute[5];
	table_1.attributes[0]= new HtmlAttribute("width", "\"100%\"");
	table_1.attributes[1]= new HtmlAttribute("border", "0");
	table_1.attributes[2]= new HtmlAttribute("cellspacing", "0");
	table_1.attributes[3]= new HtmlAttribute("cellpadding", "0");
	table_1.attributes[4]= new HtmlAttribute("bgcolor", "\"#FFCC00\"");
	table_1.subElements= new HtmlElement[1];
	body_0.subElements[9]= table_1;
	HTableRow tableRow_1= new HTableRow();
	tableRow_1.subElements= new HtmlElement[2];
	table_1.subElements[0]= tableRow_1;
	HTableData tableData_2= new HTableData();
	tableData_2.subElements= new HtmlElement[2];
	tableRow_1.subElements[0]= tableData_2;
	HImg img_0= new HImg();
	img_0.attributes= new HtmlAttribute[6];
	img_0.attributes[0]= new HtmlAttribute("src", "\"/Images/Headers/cnet-1002-title-sm.gif\"");
	img_0.attributes[1]= new HtmlAttribute("width", "370");
	img_0.attributes[2]= new HtmlAttribute("height", "55");
	img_0.attributes[3]= new HtmlAttribute("alt", "\"Personal Technology\"");
	img_0.attributes[4]= new HtmlAttribute("border", "0");
	img_0.attributes[5]= new HtmlAttribute("usemap", "\"#redball\"");
	tableData_2.subElements[0]= img_0;
	HBreak break_0= new HBreak();
	tableData_2.subElements[1]= break_0;
	HTableData tableData_3= new HTableData();
	tableData_3.attributes= new HtmlAttribute[1];
	tableData_3.attributes[0]= new HtmlAttribute("align", "right");
	tableData_3.subElements= new HtmlElement[2];
	tableRow_1.subElements[1]= tableData_3;
	HPcData pcData_35= new HPcData();
	pcData_35.setValue(" ");
	tableData_3.subElements[0]= pcData_35;
	HTable table_2= new HTable();
	table_2.attributes= new HtmlAttribute[4];
	table_2.attributes[0]= new HtmlAttribute("border", "0");
	table_2.attributes[1]= new HtmlAttribute("cellspacing", "0");
	table_2.attributes[2]= new HtmlAttribute("cellpadding", "1");
	table_2.attributes[3]= new HtmlAttribute("bgcolor", "\"#FFCC00\"");
	table_2.subElements= new HtmlElement[2];
	tableData_3.subElements[1]= table_2;
	HTableRow tableRow_2= new HTableRow();
	tableRow_2.subElements= new HtmlElement[2];
	table_2.subElements[0]= tableRow_2;
	HTableData tableData_4= new HTableData();
	tableData_4.attributes= new HtmlAttribute[2];
	tableData_4.attributes[0]= new HtmlAttribute("align", "right");
	tableData_4.attributes[1]= new HtmlAttribute("valign", "middle");
	tableData_4.subElements= new HtmlElement[1];
	tableRow_2.subElements[0]= tableData_4;
	HFont font_13= new HFont();
	font_13.attributes= new HtmlAttribute[2];
	font_13.attributes[0]= new HtmlAttribute("face", "\"Arial, Helvetica\"");
	font_13.attributes[1]= new HtmlAttribute("size", "\"-1\"");
	font_13.subElements= new HtmlElement[1];
	tableData_4.subElements[0]= font_13;
	HBold bold_11= new HBold();
	bold_11.subElements= new HtmlElement[1];
	font_13.subElements[0]= bold_11;
	HPcData pcData_36= new HPcData();
	pcData_36.setValue("Search");
	bold_11.subElements[0]= pcData_36;
	HTableData tableData_5= new HTableData();
	tableData_5.subElements= new HtmlElement[2];
	tableRow_2.subElements[1]= tableData_5;
	HInput input_0= new HInput();
	input_0.attributes= new HtmlAttribute[4];
	input_0.attributes[0]= new HtmlAttribute("name", "\"qt\"");
	input_0.attributes[1]= new HtmlAttribute("value", "\"\"");
	input_0.attributes[2]= new HtmlAttribute("size", "\"13\"");
	input_0.attributes[3]= new HtmlAttribute("maxlength", "\"255\"");
	tableData_5.subElements[0]= input_0;
	HInput input_1= new HInput();
	input_1.attributes= new HtmlAttribute[3];
	input_1.attributes[0]= new HtmlAttribute("type", "\"submit\"");
	input_1.attributes[1]= new HtmlAttribute("name", "\"formbutton\"");
	input_1.attributes[2]= new HtmlAttribute("value", "\"Go!\"");
	tableData_5.subElements[1]= input_1;
	HTableRow tableRow_3= new HTableRow();
	tableRow_3.subElements= new HtmlElement[2];
	table_2.subElements[1]= tableRow_3;
	HTableData tableData_6= new HTableData();
	tableData_6.subElements= new HtmlElement[1];
	tableRow_3.subElements[0]= tableData_6;
	HFont font_14= new HFont();
	font_14.attributes= new HtmlAttribute[2];
	font_14.attributes[0]= new HtmlAttribute("face", "\"Arial, Helvetica\"");
	font_14.attributes[1]= new HtmlAttribute("size", "\"-2\"");
	font_14.subElements= new HtmlElement[2];
	tableData_6.subElements[0]= font_14;
	HAnchor anchor_11= new HAnchor();
	anchor_11.attributes= new HtmlAttribute[1];
	anchor_11.attributes[0]= new HtmlAttribute("href", "\"/news/search/advanced/0,10163,,00.html?tag=st.cn.1006-ron.\"");
	anchor_11.subElements= new HtmlElement[1];
	font_14.subElements[0]= anchor_11;
	HPcData pcData_37= new HPcData();
	pcData_37.setValue("Advanced");
	anchor_11.subElements[0]= pcData_37;
	HAnchor anchor_12= new HAnchor();
	anchor_12.attributes= new HtmlAttribute[1];
	anchor_12.attributes[0]= new HtmlAttribute("href", "\"/search/tips/0,10066,0-0,00.html?tag=st.cn.1006-ron.usbstp\"");
	anchor_12.subElements= new HtmlElement[1];
	font_14.subElements[1]= anchor_12;
	HPcData pcData_38= new HPcData();
	pcData_38.setValue("Tips");
	anchor_12.subElements[0]= pcData_38;
	HTableData tableData_7= new HTableData();
	tableData_7.attributes= new HtmlAttribute[2];
	tableData_7.attributes[0]= new HtmlAttribute("align", "\"left\"");
	tableData_7.attributes[1]= new HtmlAttribute("valign", "\"middle\"");
	tableData_7.subElements= new HtmlElement[1];
	tableRow_3.subElements[1]= tableData_7;
	HFont font_15= new HFont();
	font_15.attributes= new HtmlAttribute[2];
	font_15.attributes[0]= new HtmlAttribute("face", "\"Arial, Helvetica\"");
	font_15.attributes[1]= new HtmlAttribute("size", "\"-1\"");
	font_15.subElements= new HtmlElement[1];
	tableData_7.subElements[0]= font_15;
	HSelect select_0= new HSelect();
	select_0.attributes= new HtmlAttribute[1];
	select_0.attributes[0]= new HtmlAttribute("name", "\"tg\"");
	select_0.subElements= new HtmlElement[1];
	font_15.subElements[0]= select_0;
	HOption option_0= new HOption();
	option_0.attributes= new HtmlAttribute[8];
	option_0.attributes[0]= new HtmlAttribute("value", "\"ne-1002\"");
	option_0.attributes[1]= new HtmlAttribute("(null)", "\"100%\"");
	option_0.attributes[2]= new HtmlAttribute("(null)", "\"0\"");
	option_0.attributes[3]= new HtmlAttribute("(null)", "\"5\"");
	option_0.attributes[4]= new HtmlAttribute("(null)", "\"1\"");
	option_0.attributes[5]= new HtmlAttribute("(null)", "\"top\"");
	option_0.attributes[6]= new HtmlAttribute("(null)", "\"arial, helvetica\"");
	option_0.attributes[7]= new HtmlAttribute("(null)", "\"#006633\"");
	option_0.subElements= new HtmlElement[462];
	select_0.subElements[0]= option_0;
	HPcData pcData_39= new HPcData();
	pcData_39.setValue("In News");
	option_0.subElements[0]= pcData_39;
	HPcData pcData_40= new HPcData();
	pcData_40.setValue("All CNET");
	option_0.subElements[1]= pcData_40;
	HPcData pcData_41= new HPcData();
	pcData_41.setValue("\r\n			");
	option_0.subElements[2]= pcData_41;
	HPcData pcData_42= new HPcData();
	pcData_42.setValue("The Web\r\n			");
	option_0.subElements[3]= pcData_42;
	HPcData pcData_43= new HPcData();
	pcData_43.setValue("\r\n	        ");
	option_0.subElements[4]= pcData_43;
	HComment comment_3= new HComment();
	comment_3.setValue(" leo loves you --");
	option_0.subElements[5]= comment_3;
	HPcData pcData_44= new HPcData();
	pcData_44.setValue("\r\n			");
	option_0.subElements[6]= pcData_44;
	HPcData pcData_45= new HPcData();
	pcData_45.setValue("\r\n			");
	option_0.subElements[7]= pcData_45;
	HPcData pcData_46= new HPcData();
	pcData_46.setValue("\r\n			");
	option_0.subElements[8]= pcData_46;
	HPcData pcData_47= new HPcData();
	pcData_47.setValue("\r\n		\r\n		");
	option_0.subElements[9]= pcData_47;
	HPcData pcData_48= new HPcData();
	pcData_48.setValue("\r\n		");
	option_0.subElements[10]= pcData_48;
	HPcData pcData_49= new HPcData();
	pcData_49.setValue("\r\n		");
	option_0.subElements[11]= pcData_49;
	HPcData pcData_50= new HPcData();
	pcData_50.setValue("\r\n		");
	option_0.subElements[12]= pcData_50;
	HPcData pcData_51= new HPcData();
	pcData_51.setValue("\r\n		");
	option_0.subElements[13]= pcData_51;
	HPcData pcData_52= new HPcData();
	pcData_52.setValue("\r\n		");
	option_0.subElements[14]= pcData_52;
	HPcData pcData_53= new HPcData();
	pcData_53.setValue("\r\n		");
	option_0.subElements[15]= pcData_53;
	HPcData pcData_54= new HPcData();
	pcData_54.setValue("\r\n		");
	option_0.subElements[16]= pcData_54;
	HPcData pcData_55= new HPcData();
	pcData_55.setValue("\r\n		");
	option_0.subElements[17]= pcData_55;
	HPcData pcData_56= new HPcData();
	pcData_56.setValue("\r\n		");
	option_0.subElements[18]= pcData_56;
	HPcData pcData_57= new HPcData();
	pcData_57.setValue("\r\n		");
	option_0.subElements[19]= pcData_57;
	HPcData pcData_58= new HPcData();
	pcData_58.setValue("\r\n	");
	option_0.subElements[20]= pcData_58;
	HPcData pcData_59= new HPcData();
	pcData_59.setValue("\"Buy at Fujitsu PC Direct. Click Now!\"");
	option_0.subElements[21]= pcData_59;
	HPcData pcData_60= new HPcData();
	pcData_60.setValue("		\r\n		\r\n");
	option_0.subElements[22]= pcData_60;
	HComment comment_4= new HComment();
	comment_4.setValue(" Breadcrumb --");
	option_0.subElements[23]= comment_4;
	HPcData pcData_61= new HPcData();
	pcData_61.setValue("\r\n");
	option_0.subElements[24]= pcData_61;
	HPcData pcData_62= new HPcData();
	pcData_62.setValue("\r\n        ");
	option_0.subElements[25]= pcData_62;
	HPcData pcData_63= new HPcData();
	pcData_63.setValue("CNET");
	option_0.subElements[26]= pcData_63;
	HPcData pcData_64= new HPcData();
	pcData_64.setValue(" : ");
	option_0.subElements[27]= pcData_64;
	HPcData pcData_65= new HPcData();
	pcData_65.setValue("News");
	option_0.subElements[28]= pcData_65;
	HPcData pcData_66= new HPcData();
	pcData_66.setValue(" : ");
	option_0.subElements[29]= pcData_66;
	HPcData pcData_67= new HPcData();
	pcData_67.setValue("Personal Technology");
	option_0.subElements[30]= pcData_67;
	HPcData pcData_68= new HPcData();
	pcData_68.setValue(" : ");
	option_0.subElements[31]= pcData_68;
	HPcData pcData_69= new HPcData();
	pcData_69.setValue("Story");
	option_0.subElements[32]= pcData_69;
	HPcData pcData_70= new HPcData();
	pcData_70.setValue("\r\n			");
	option_0.subElements[33]= pcData_70;
	HPcData pcData_71= new HPcData();
	pcData_71.setValue("\r\n");
	option_0.subElements[34]= pcData_71;
	HPcData pcData_72= new HPcData();
	pcData_72.setValue("\r\n");
	option_0.subElements[35]= pcData_72;
	HComment comment_5= new HComment();
	comment_5.setValue(" /Breadcrumb --");
	option_0.subElements[36]= comment_5;
	HPcData pcData_73= new HPcData();
	pcData_73.setValue("\r\n   		\r\n");
	option_0.subElements[37]= pcData_73;
	HPcData pcData_74= new HPcData();
	pcData_74.setValue("\r\n");
	option_0.subElements[38]= pcData_74;
	HPcData pcData_75= new HPcData();
	pcData_75.setValue("\r\n");
	option_0.subElements[39]= pcData_75;
	HPcData pcData_76= new HPcData();
	pcData_76.setValue("\r\n\r\n\r\n");
	option_0.subElements[40]= pcData_76;
	HPcData pcData_77= new HPcData();
	pcData_77.setValue("ADVERTISEMENT");
	option_0.subElements[41]= pcData_77;
	HPcData pcData_78= new HPcData();
	pcData_78.setValue("\r\n\r\n");
	option_0.subElements[42]= pcData_78;
	HPcData pcData_79= new HPcData();
	pcData_79.setValue("\r\n\r\n\r\n");
	option_0.subElements[43]= pcData_79;
	HComment comment_6= new HComment();
	comment_6.setValue(" Vignette StoryServer 4 Thu Dec 16 10:46:01 1999 --");
	option_0.subElements[44]= comment_6;
	HPcData pcData_80= new HPcData();
	pcData_80.setValue("\r\n\r\n\r\n\r\n");
	option_0.subElements[45]= pcData_80;
	HPcData pcData_81= new HPcData();
	pcData_81.setValue("Latest Headlines");
	option_0.subElements[46]= pcData_81;
	HPcData pcData_82= new HPcData();
	pcData_82.setValue("display on desktop");
	option_0.subElements[47]= pcData_82;
	HPcData pcData_83= new HPcData();
	pcData_83.setValue("\r\n");
	option_0.subElements[48]= pcData_83;
	HPcData pcData_84= new HPcData();
	pcData_84.setValue("\r\n");
	option_0.subElements[49]= pcData_84;
	HPcData pcData_85= new HPcData();
	pcData_85.setValue("\r\n");
	option_0.subElements[50]= pcData_85;
	HPcData pcData_86= new HPcData();
	pcData_86.setValue("\r\n");
	option_0.subElements[51]= pcData_86;
	HPcData pcData_87= new HPcData();
	pcData_87.setValue("\r\n");
	option_0.subElements[52]= pcData_87;
	HPcData pcData_88= new HPcData();
	pcData_88.setValue("\r\n");
	option_0.subElements[53]= pcData_88;
	HPcData pcData_89= new HPcData();
	pcData_89.setValue("\r\n");
	option_0.subElements[54]= pcData_89;
	HPcData pcData_90= new HPcData();
	pcData_90.setValue("Enterprise Computing");
	option_0.subElements[55]= pcData_90;
	HPcData pcData_91= new HPcData();
	pcData_91.setValue("EU court issues Microsoft ruling");
	option_0.subElements[56]= pcData_91;
	HPcData pcData_92= new HPcData();
	pcData_92.setValue("Indirect computer dealers struggle");
	option_0.subElements[57]= pcData_92;
	HPcData pcData_93= new HPcData();
	pcData_93.setValue("\r\n");
	option_0.subElements[58]= pcData_93;
	HPcData pcData_94= new HPcData();
	pcData_94.setValue("\r\n");
	option_0.subElements[59]= pcData_94;
	HPcData pcData_95= new HPcData();
	pcData_95.setValue("\r\n");
	option_0.subElements[60]= pcData_95;
	HPcData pcData_96= new HPcData();
	pcData_96.setValue("\r\n");
	option_0.subElements[61]= pcData_96;
	HPcData pcData_97= new HPcData();
	pcData_97.setValue("\r\n");
	option_0.subElements[62]= pcData_97;
	HPcData pcData_98= new HPcData();
	pcData_98.setValue("Communications");
	option_0.subElements[63]= pcData_98;
	HPcData pcData_99= new HPcData();
	pcData_99.setValue("Japan catches telecom merger fever");
	option_0.subElements[64]= pcData_99;
	HPcData pcData_100= new HPcData();
	pcData_100.setValue("Qwest, BellSouth win $250 million in contracts");
	option_0.subElements[65]= pcData_100;
	HPcData pcData_101= new HPcData();
	pcData_101.setValue("\r\n");
	option_0.subElements[66]= pcData_101;
	HPcData pcData_102= new HPcData();
	pcData_102.setValue("\r\n");
	option_0.subElements[67]= pcData_102;
	HPcData pcData_103= new HPcData();
	pcData_103.setValue("\r\n");
	option_0.subElements[68]= pcData_103;
	HPcData pcData_104= new HPcData();
	pcData_104.setValue("\r\n");
	option_0.subElements[69]= pcData_104;
	HPcData pcData_105= new HPcData();
	pcData_105.setValue("\r\n");
	option_0.subElements[70]= pcData_105;
	HPcData pcData_106= new HPcData();
	pcData_106.setValue("The Net");
	option_0.subElements[71]= pcData_106;
	HPcData pcData_107= new HPcData();
	pcData_107.setValue("Tommy Hilfiger styles Web site with Net music");
	option_0.subElements[72]= pcData_107;
	HPcData pcData_108= new HPcData();
	pcData_108.setValue("CMGI climbs on stock split announcement");
	option_0.subElements[73]= pcData_108;
	HPcData pcData_109= new HPcData();
	pcData_109.setValue("Sony, Time Warner face the music on CD pricing");
	option_0.subElements[74]= pcData_109;
	HPcData pcData_110= new HPcData();
	pcData_110.setValue("Microsoft offers technical support with Ask Maxwell");
	option_0.subElements[75]= pcData_110;
	HPcData pcData_111= new HPcData();
	pcData_111.setValue("\r\n");
	option_0.subElements[76]= pcData_111;
	HPcData pcData_112= new HPcData();
	pcData_112.setValue("\r\n");
	option_0.subElements[77]= pcData_112;
	HPcData pcData_113= new HPcData();
	pcData_113.setValue("\r\n");
	option_0.subElements[78]= pcData_113;
	HPcData pcData_114= new HPcData();
	pcData_114.setValue("\r\n");
	option_0.subElements[79]= pcData_114;
	HPcData pcData_115= new HPcData();
	pcData_115.setValue("\r\n");
	option_0.subElements[80]= pcData_115;
	HPcData pcData_116= new HPcData();
	pcData_116.setValue("Personal Technology");
	option_0.subElements[81]= pcData_116;
	HPcData pcData_117= new HPcData();
	pcData_117.setValue("Cable set-top boxes instead of phones?");
	option_0.subElements[82]= pcData_117;
	HPcData pcData_118= new HPcData();
	pcData_118.setValue("\r\n");
	option_0.subElements[83]= pcData_118;
	HPcData pcData_119= new HPcData();
	pcData_119.setValue("\r\n");
	option_0.subElements[84]= pcData_119;
	HPcData pcData_120= new HPcData();
	pcData_120.setValue("\r\n");
	option_0.subElements[85]= pcData_120;
	HPcData pcData_121= new HPcData();
	pcData_121.setValue("\r\n");
	option_0.subElements[86]= pcData_121;
	HPcData pcData_122= new HPcData();
	pcData_122.setValue("\r\n");
	option_0.subElements[87]= pcData_122;
	HPcData pcData_123= new HPcData();
	pcData_123.setValue("E-commerce");
	option_0.subElements[88]= pcData_123;
	HPcData pcData_124= new HPcData();
	pcData_124.setValue("Microsoft, Best Buy in marketing pact");
	option_0.subElements[89]= pcData_124;
	HPcData pcData_125= new HPcData();
	pcData_125.setValue("GM drives Saturn dealers to Web");
	option_0.subElements[90]= pcData_125;
	HPcData pcData_126= new HPcData();
	pcData_126.setValue("Barbie, Hot Wheels PCs lag in holiday crunch");
	option_0.subElements[91]= pcData_126;
	HPcData pcData_127= new HPcData();
	pcData_127.setValue("Portals pair off with retail giants");
	option_0.subElements[92]= pcData_127;
	HPcData pcData_128= new HPcData();
	pcData_128.setValue("K-tel stock jumps on Linux allure");
	option_0.subElements[93]= pcData_128;
	HPcData pcData_129= new HPcData();
	pcData_129.setValue("\r\n");
	option_0.subElements[94]= pcData_129;
	HPcData pcData_130= new HPcData();
	pcData_130.setValue("\r\n");
	option_0.subElements[95]= pcData_130;
	HPcData pcData_131= new HPcData();
	pcData_131.setValue("\r\n");
	option_0.subElements[96]= pcData_131;
	HPcData pcData_132= new HPcData();
	pcData_132.setValue("\r\n");
	option_0.subElements[97]= pcData_132;
	HPcData pcData_133= new HPcData();
	pcData_133.setValue("\r\n");
	option_0.subElements[98]= pcData_133;
	HPcData pcData_134= new HPcData();
	pcData_134.setValue("Services & Consulting");
	option_0.subElements[99]= pcData_134;
	HPcData pcData_135= new HPcData();
	pcData_135.setValue("Ariba to expand Net market role with Tradex");
	option_0.subElements[100]= pcData_135;
	HPcData pcData_136= new HPcData();
	pcData_136.setValue("Net consultant jumps 57 percent on IPO");
	option_0.subElements[101]= pcData_136;
	HPcData pcData_137= new HPcData();
	pcData_137.setValue("3Com takes $100 million stake in USWeb/CKS");
	option_0.subElements[102]= pcData_137;
	HPcData pcData_138= new HPcData();
	pcData_138.setValue("\r\n");
	option_0.subElements[103]= pcData_138;
	HPcData pcData_139= new HPcData();
	pcData_139.setValue("\r\n");
	option_0.subElements[104]= pcData_139;
	HPcData pcData_140= new HPcData();
	pcData_140.setValue("\r\n");
	option_0.subElements[105]= pcData_140;
	HPcData pcData_141= new HPcData();
	pcData_141.setValue("\r\n");
	option_0.subElements[106]= pcData_141;
	HPcData pcData_142= new HPcData();
	pcData_142.setValue("\r\n");
	option_0.subElements[107]= pcData_142;
	HPcData pcData_143= new HPcData();
	pcData_143.setValue("Year 2000");
	option_0.subElements[108]= pcData_143;
	HPcData pcData_144= new HPcData();
	pcData_144.setValue("Far east nations will signal Y2K dangers");
	option_0.subElements[109]= pcData_144;
	HPcData pcData_145= new HPcData();
	pcData_145.setValue("Did you miss a day?");
	option_0.subElements[110]= pcData_145;
	HPcData pcData_146= new HPcData();
	pcData_146.setValue("One Week View");
	option_0.subElements[111]= pcData_146;
	HPcData pcData_147= new HPcData();
	pcData_147.setValue("\r\n");
	option_0.subElements[112]= pcData_147;
	HComment comment_7= new HComment();
	comment_7.setValue(" NuggetID=1005 Branding-CN --");
	option_0.subElements[113]= comment_7;
	HComment comment_8= new HComment();
	comment_8.setValue(" Constant -end part 1 --");
	option_0.subElements[114]= comment_8;
	HPcData pcData_148= new HPcData();
	pcData_148.setValue(" ");
	option_0.subElements[115]= pcData_148;
	HPcData pcData_149= new HPcData();
	pcData_149.setValue("Short Term");
	option_0.subElements[116]= pcData_149;
	HPcData pcData_150= new HPcData();
	pcData_150.setValue("Health Insurance Online");
	option_0.subElements[117]= pcData_150;
	HPcData pcData_151= new HPcData();
	pcData_151.setValue(" ");
	option_0.subElements[118]= pcData_151;
	HPcData pcData_152= new HPcData();
	pcData_152.setValue("Temporarily out of work?");
	option_0.subElements[119]= pcData_152;
	HPcData pcData_153= new HPcData();
	pcData_153.setValue(" ");
	option_0.subElements[120]= pcData_153;
	HPcData pcData_154= new HPcData();
	pcData_154.setValue("Get 30-185 day coverage!");
	option_0.subElements[121]= pcData_154;
	HPcData pcData_155= new HPcData();
	pcData_155.setValue(" ");
	option_0.subElements[122]= pcData_155;
	HPcData pcData_156= new HPcData();
	pcData_156.setValue("HealthAxis.com");
	option_0.subElements[123]= pcData_156;
	HComment comment_9= new HComment();
	comment_9.setValue(" Constant - begin part 2 --");
	option_0.subElements[124]= comment_9;
	HComment comment_10= new HComment();
	comment_10.setValue(" Constant - end part2 --");
	option_0.subElements[125]= comment_10;
	HComment comment_11= new HComment();
	comment_11.setValue(" End 1005 Branding-CN --");
	option_0.subElements[126]= comment_11;
	HPcData pcData_157= new HPcData();
	pcData_157.setValue("\r\n");
	option_0.subElements[127]= pcData_157;
	HPcData pcData_158= new HPcData();
	pcData_158.setValue("\r\n");
	option_0.subElements[128]= pcData_158;
	HPcData pcData_159= new HPcData();
	pcData_159.setValue("\r\n\r\n");
	option_0.subElements[129]= pcData_159;
	HPcData pcData_160= new HPcData();
	pcData_160.setValue("\r\n");
	option_0.subElements[130]= pcData_160;
	HPcData pcData_161= new HPcData();
	pcData_161.setValue("Related news");
	option_0.subElements[131]= pcData_161;
	HPcData pcData_162= new HPcData();
	pcData_162.setValue("Message Boards");
	option_0.subElements[132]= pcData_162;
	HPcData pcData_163= new HPcData();
	pcData_163.setValue("See Story in Context");
	option_0.subElements[133]= pcData_163;
	HPcData pcData_164= new HPcData();
	pcData_164.setValue("Search");
	option_0.subElements[134]= pcData_164;
	HPcData pcData_165= new HPcData();
	pcData_165.setValue("\r\n");
	option_0.subElements[135]= pcData_165;
	HPcData pcData_166= new HPcData();
	pcData_166.setValue("\r\n\r\n\r\n");
	option_0.subElements[136]= pcData_166;
	HPcData pcData_167= new HPcData();
	pcData_167.setValue("\r\n");
	option_0.subElements[137]= pcData_167;
	HPcData pcData_168= new HPcData();
	pcData_168.setValue("\r\n");
	option_0.subElements[138]= pcData_168;
	HPcData pcData_169= new HPcData();
	pcData_169.setValue("Cable set-top boxes instead of phones?");
	option_0.subElements[139]= pcData_169;
	HPcData pcData_170= new HPcData();
	pcData_170.setValue("\r\n");
	option_0.subElements[140]= pcData_170;
	HPcData pcData_171= new HPcData();
	pcData_171.setValue("By ");
	option_0.subElements[141]= pcData_171;
	HPcData pcData_172= new HPcData();
	pcData_172.setValue("Jim Davis");
	option_0.subElements[142]= pcData_172;
	HPcData pcData_173= new HPcData();
	pcData_173.setValue("Staff Writer, CNET News.com");
	option_0.subElements[143]= pcData_173;
	HPcData pcData_174= new HPcData();
	pcData_174.setValue("\r\nDecember 16, 1999, 9:30 a.m. PT");
	option_0.subElements[144]= pcData_174;
	HPcData pcData_175= new HPcData();
	pcData_175.setValue("\r\n\r\n\r\n");
	option_0.subElements[145]= pcData_175;
	HPcData pcData_176= new HPcData();
	pcData_176.setValue(" \r\n");
	option_0.subElements[146]= pcData_176;
	HComment comment_12= new HComment();
	comment_12.setValue(" EDS UPDATE 10:00 am: Corrects company name as \"Lucent Technologies\" on first reference in graf 2, corrects company name as \"Tele-Communications Inc.\" on first reference in graf 5, adds \"pending deal with\" in graf 5, changes \"telcos\" to \"telephone companies\" in graf 5, removes hyphens in Time Warner in graf 9 and graf 11 --");
	option_0.subElements[147]= comment_12;
	HPcData pcData_177= new HPcData();
	pcData_177.setValue("\r\r\n\r\r\n");
	option_0.subElements[148]= pcData_177;
	HPcData pcData_178= new HPcData();
	pcData_178.setValue("Will next generation cable set-top boxes replace your phone?\r\r\n");
	option_0.subElements[149]= pcData_178;
	HPcData pcData_179= new HPcData();
	pcData_179.setValue("\r\r\n\r\r\nProbably not. But the companies seem like they're trying. Companies such as General Instrument and Lucent Technologies are hard at work on integrating hardware and software so that cable operators like AT");
	option_0.subElements[150]= pcData_179;
	HPcData pcData_180= new HPcData();
	pcData_180.setValue(" and Time Warner can bundle telephony services along with a package of Internet access, video programming and even wireless phone service.\r\r\n");
	option_0.subElements[151]= pcData_180;
	HPcData pcData_181= new HPcData();
	pcData_181.setValue("\r\r\n\"Voice is really the killer applications for data-over-cable services because it's such a huge business already,\" said Lief Koepsel, director of marketing for Com21, one of the four largest cable modem equipment makers. \"In the same way people can choose between gas and electric, they will be offered data services from the telco or cable company in 10 years.\"\r\r\n");
	option_0.subElements[152]= pcData_181;
	HPcData pcData_182= new HPcData();
	pcData_182.setValue("\r\r\n");
	option_0.subElements[153]= pcData_182;
	HPcData pcData_183= new HPcData();
	pcData_183.setValue("Quote Snapshot");
	option_0.subElements[154]= pcData_183;
	HComment comment_13= new HComment();
	comment_13.setValue(" Vignette StoryServer 4 Thu Dec 16 10:49:48 1999 --");
	option_0.subElements[155]= comment_13;
	HPcData pcData_184= new HPcData();
	pcData_184.setValue("\r\n\r\n	\r\n				\r\n		\r\n		");
	option_0.subElements[156]= pcData_184;
	HPcData pcData_185= new HPcData();
	pcData_185.setValue("\r\n		");
	option_0.subElements[157]= pcData_185;
	HPcData pcData_186= new HPcData();
	pcData_186.setValue("\r\n		\r\n		\r\n		");
	option_0.subElements[158]= pcData_186;
	HPcData pcData_187= new HPcData();
	pcData_187.setValue("\r\n		\r\n			");
	option_0.subElements[159]= pcData_187;
	HPcData pcData_188= new HPcData();
	pcData_188.setValue("T");
	option_0.subElements[160]= pcData_188;
	HPcData pcData_189= new HPcData();
	pcData_189.setValue("				");
	option_0.subElements[161]= pcData_189;
	HPcData pcData_190= new HPcData();
	pcData_190.setValue("\r\n		\r\n		\r\n		\r\n			");
	option_0.subElements[162]= pcData_190;
	HPcData pcData_191= new HPcData();
	pcData_191.setValue("53.00");
	option_0.subElements[163]= pcData_191;
	HPcData pcData_192= new HPcData();
	pcData_192.setValue("\r\n				\r\n		\r\n		");
	option_0.subElements[164]= pcData_192;
	HPcData pcData_193= new HPcData();
	pcData_193.setValue("-1.50");
	option_0.subElements[165]= pcData_193;
	HPcData pcData_194= new HPcData();
	pcData_194.setValue("\r\n		\r\n		");
	option_0.subElements[166]= pcData_194;
	HPcData pcData_195= new HPcData();
	pcData_195.setValue("\r\n	");
	option_0.subElements[167]= pcData_195;
	HComment comment_14= new HComment();
	comment_14.setValue(" Vignette StoryServer 4 Thu Dec 16 10:50:18 1999 --");
	option_0.subElements[168]= comment_14;
	HPcData pcData_196= new HPcData();
	pcData_196.setValue("\r\n\r\n	\r\n				\r\n		\r\n		");
	option_0.subElements[169]= pcData_196;
	HPcData pcData_197= new HPcData();
	pcData_197.setValue("\r\n		");
	option_0.subElements[170]= pcData_197;
	HPcData pcData_198= new HPcData();
	pcData_198.setValue("\r\n		\r\n		\r\n		");
	option_0.subElements[171]= pcData_198;
	HPcData pcData_199= new HPcData();
	pcData_199.setValue("\r\n		\r\n			");
	option_0.subElements[172]= pcData_199;
	HPcData pcData_200= new HPcData();
	pcData_200.setValue("GIC");
	option_0.subElements[173]= pcData_200;
	HPcData pcData_201= new HPcData();
	pcData_201.setValue("				");
	option_0.subElements[174]= pcData_201;
	HPcData pcData_202= new HPcData();
	pcData_202.setValue("\r\n		\r\n		\r\n		\r\n			");
	option_0.subElements[175]= pcData_202;
	HPcData pcData_203= new HPcData();
	pcData_203.setValue("73.00");
	option_0.subElements[176]= pcData_203;
	HPcData pcData_204= new HPcData();
	pcData_204.setValue("\r\n				\r\n		\r\n		");
	option_0.subElements[177]= pcData_204;
	HPcData pcData_205= new HPcData();
	pcData_205.setValue("-0.56");
	option_0.subElements[178]= pcData_205;
	HPcData pcData_206= new HPcData();
	pcData_206.setValue("\r\n		\r\n		");
	option_0.subElements[179]= pcData_206;
	HPcData pcData_207= new HPcData();
	pcData_207.setValue("\r\n	");
	option_0.subElements[180]= pcData_207;
	HComment comment_15= new HComment();
	comment_15.setValue(" Vignette StoryServer 4 Thu Dec 16 10:49:55 1999 --");
	option_0.subElements[181]= comment_15;
	HPcData pcData_208= new HPcData();
	pcData_208.setValue("\r\n\r\n	\r\n				\r\n		\r\n		");
	option_0.subElements[182]= pcData_208;
	HPcData pcData_209= new HPcData();
	pcData_209.setValue("\r\n		");
	option_0.subElements[183]= pcData_209;
	HPcData pcData_210= new HPcData();
	pcData_210.setValue("\r\n		\r\n		\r\n		");
	option_0.subElements[184]= pcData_210;
	HPcData pcData_211= new HPcData();
	pcData_211.setValue("\r\n		\r\n			");
	option_0.subElements[185]= pcData_211;
	HPcData pcData_212= new HPcData();
	pcData_212.setValue("MOT");
	option_0.subElements[186]= pcData_212;
	HPcData pcData_213= new HPcData();
	pcData_213.setValue("				");
	option_0.subElements[187]= pcData_213;
	HPcData pcData_214= new HPcData();
	pcData_214.setValue("\r\n		\r\n		\r\n		\r\n			");
	option_0.subElements[188]= pcData_214;
	HPcData pcData_215= new HPcData();
	pcData_215.setValue("128.00");
	option_0.subElements[189]= pcData_215;
	HPcData pcData_216= new HPcData();
	pcData_216.setValue("\r\n				\r\n		\r\n		");
	option_0.subElements[190]= pcData_216;
	HPcData pcData_217= new HPcData();
	pcData_217.setValue("-2.19");
	option_0.subElements[191]= pcData_217;
	HPcData pcData_218= new HPcData();
	pcData_218.setValue("\r\n		\r\n		");
	option_0.subElements[192]= pcData_218;
	HPcData pcData_219= new HPcData();
	pcData_219.setValue("\r\n	");
	option_0.subElements[193]= pcData_219;
	HComment comment_16= new HComment();
	comment_16.setValue(" Vignette StoryServer 4 Thu Dec 16 10:49:08 1999 --");
	option_0.subElements[194]= comment_16;
	HPcData pcData_220= new HPcData();
	pcData_220.setValue("\r\n\r\n	\r\n				\r\n		\r\n		");
	option_0.subElements[195]= pcData_220;
	HPcData pcData_221= new HPcData();
	pcData_221.setValue("\r\n		");
	option_0.subElements[196]= pcData_221;
	HPcData pcData_222= new HPcData();
	pcData_222.setValue("\r\n		\r\n		\r\n		");
	option_0.subElements[197]= pcData_222;
	HPcData pcData_223= new HPcData();
	pcData_223.setValue("\r\n		\r\n			");
	option_0.subElements[198]= pcData_223;
	HPcData pcData_224= new HPcData();
	pcData_224.setValue("CMTO");
	option_0.subElements[199]= pcData_224;
	HPcData pcData_225= new HPcData();
	pcData_225.setValue("				");
	option_0.subElements[200]= pcData_225;
	HPcData pcData_226= new HPcData();
	pcData_226.setValue("\r\n		\r\n		\r\n		\r\n			");
	option_0.subElements[201]= pcData_226;
	HPcData pcData_227= new HPcData();
	pcData_227.setValue("25.50");
	option_0.subElements[202]= pcData_227;
	HPcData pcData_228= new HPcData();
	pcData_228.setValue("\r\n				\r\n		\r\n		");
	option_0.subElements[203]= pcData_228;
	HPcData pcData_229= new HPcData();
	pcData_229.setValue("-0.56");
	option_0.subElements[204]= pcData_229;
	HPcData pcData_230= new HPcData();
	pcData_230.setValue("\r\n		\r\n		");
	option_0.subElements[205]= pcData_230;
	HPcData pcData_231= new HPcData();
	pcData_231.setValue("\r\n	");
	option_0.subElements[206]= pcData_231;
	HPcData pcData_232= new HPcData();
	pcData_232.setValue("Enter symbol:");
	option_0.subElements[207]= pcData_232;
	HPcData pcData_233= new HPcData();
	pcData_233.setValue(" ");
	option_0.subElements[208]= pcData_233;
	HPcData pcData_234= new HPcData();
	pcData_234.setValue("Symbol");
	option_0.subElements[209]= pcData_234;
	HPcData pcData_235= new HPcData();
	pcData_235.setValue("Lookup");
	option_0.subElements[210]= pcData_235;
	HPcData pcData_236= new HPcData();
	pcData_236.setValue("More from CNET Investor");
	option_0.subElements[211]= pcData_236;
	HPcData pcData_237= new HPcData();
	pcData_237.setValue("Quotes delayed 20+ minutes");
	option_0.subElements[212]= pcData_237;
	HPcData pcData_238= new HPcData();
	pcData_238.setValue("General Instrument, which is in the process of being acquired by Motorola, has entered into a joint development and marketing agreement with Lucent. The deal means GI equipment in customer's homes will be able to talk with Lucent equipment used in a cable operator's main office, and in the process, enable lower cost telephone services to be made available sooner from cable companies, hopefully.\r\r\n");
	option_0.subElements[213]= pcData_238;
	HPcData pcData_239= new HPcData();
	pcData_239.setValue("\r\r\nAT");
	option_0.subElements[214]= pcData_239;
	HPcData pcData_240= new HPcData();
	pcData_240.setValue("'s purchase of cable operators Tele-Communications Inc. (TCI) and pending deal with Media One provides the company with a means to offer local phone service without having to go through local telephone companies like Pacific Bell or Bell Atlantic.\r\r\n");
	option_0.subElements[215]= pcData_240;
	HPcData pcData_241= new HPcData();
	pcData_241.setValue("\r\r\nBut, as is the case with many new technologies, many questions remain unresolved. Cable operators don't seem sure yet about whether telephony, video and data services will be delivered through the set-top box residing in the living room, or a new class of devices called \"residential gateways.\"\r\r\n");
	option_0.subElements[216]= pcData_241;
	HPcData pcData_242= new HPcData();
	pcData_242.setValue("\r\r\nCable operators have been looking at the set-top as a hub that phones and cameras and other devices hang off, said Dwight Sakuma, director of consumer products and services at GI. Sakuma thinks that two or three years down the road, when telephony services are more prevalent, they will eventually have to use both a gateway box and the set-top.\r\r\n");
	option_0.subElements[217]= pcData_242;
	HPcData pcData_243= new HPcData();
	pcData_243.setValue("\r\r\n");
	option_0.subElements[218]= pcData_243;
	HPcData pcData_244= new HPcData();
	pcData_244.setValue("Residential gateway appliances");
	option_0.subElements[219]= pcData_244;
	HPcData pcData_245= new HPcData();
	pcData_245.setValue(" basically look like a utility box that hangs outside a customer's home. A cable line is hooked up to the box, which then controls the flow of data to other devices such as the set-top, a PC, phones and handheld gadgets.\r\r\n");
	option_0.subElements[220]= pcData_245;
	HPcData pcData_246= new HPcData();
	pcData_246.setValue("\r\r\n\"Cable companies will try a bunch of things and see if the spaghetti sticks to the wall,\" said Jim Chiddix, Time Warner cable's chief technology officer.\r\r\n");
	option_0.subElements[221]= pcData_246;
	HPcData pcData_247= new HPcData();
	pcData_247.setValue("\r\r\nKoepsel thinks the set-top won't wind up offering telephony functions because it would require technicians to enter a customer's home for installation and repair. The current model used by telcos--they are responsible for the wire up to the utility box--works fine, he said. Com21 is eyeing the production of such devices but has not announced plans yet, he noted.\r\r\n\r\r\n");
	option_0.subElements[222]= pcData_247;
	HPcData pcData_248= new HPcData();
	pcData_248.setValue("\r\r\nIn the case of AT");
	option_0.subElements[223]= pcData_248;
	HPcData pcData_249= new HPcData();
	pcData_249.setValue(", the company signed a deal in February with Time Warner cable to provide telephony services over Time Warner's cable network. The deal hasn't been finalized as of 11 months later because AT");
	option_0.subElements[224]= pcData_249;
	HPcData pcData_250= new HPcData();
	pcData_250.setValue(" has been busy integrating Media One into its corporate structure, say Time Warner representatives.\r\r\n");
	option_0.subElements[225]= pcData_250;
	HPcData pcData_251= new HPcData();
	pcData_251.setValue("\r\r\nWith AT");
	option_0.subElements[226]= pcData_251;
	HPcData pcData_252= new HPcData();
	pcData_252.setValue(" ");
	option_0.subElements[227]= pcData_252;
	HPcData pcData_253= new HPcData();
	pcData_253.setValue("somewhat preoccupied ");
	option_0.subElements[228]= pcData_253;
	HPcData pcData_254= new HPcData();
	pcData_254.setValue(", no decisions about how to build the infrastructure for the service have been made, let alone whether the set-top or the gateway device will ultimately wind up as the main control point for data in the home.\r\r\n");
	option_0.subElements[229]= pcData_254;
	HPcData pcData_255= new HPcData();
	pcData_255.setValue("\r\r\n");
	option_0.subElements[230]= pcData_255;
	HPcData pcData_256= new HPcData();
	pcData_256.setValue("Cahners In-Stat Group");
	option_0.subElements[231]= pcData_256;
	HPcData pcData_257= new HPcData();
	pcData_257.setValue(" predicts the residential gateway market will grow from $200 million in 2000 to $2.4 billion in 2003.\r\r\n");
	option_0.subElements[232]= pcData_257;
	HPcData pcData_258= new HPcData();
	pcData_258.setValue("\r\r\n\r\r\n\r\r\n\r\r\n\r\r\n");
	option_0.subElements[233]= pcData_258;
	HPcData pcData_259= new HPcData();
	pcData_259.setValue("\r\n\r\n");
	option_0.subElements[234]= pcData_259;
	HPcData pcData_260= new HPcData();
	pcData_260.setValue(" ");
	option_0.subElements[235]= pcData_260;
	HPcData pcData_261= new HPcData();
	pcData_261.setValue("Related news stories");
	option_0.subElements[236]= pcData_261;
	HPcData pcData_262= new HPcData();
	pcData_262.setValue("Will \"residential gateway\" fuel home networking trend?");
	option_0.subElements[237]= pcData_262;
	HPcData pcData_263= new HPcData();
	pcData_263.setValue(" ");
	option_0.subElements[238]= pcData_263;
	HPcData pcData_264= new HPcData();
	pcData_264.setValue("August 3, 1999");
	option_0.subElements[239]= pcData_264;
	HPcData pcData_265= new HPcData();
	pcData_265.setValue("AT");
	option_0.subElements[240]= pcData_265;
	HPcData pcData_266= new HPcData();
	pcData_266.setValue(" finds itself trailing in cable-based phone service");
	option_0.subElements[241]= pcData_266;
	HPcData pcData_267= new HPcData();
	pcData_267.setValue(" ");
	option_0.subElements[242]= pcData_267;
	HPcData pcData_268= new HPcData();
	pcData_268.setValue("October 25, 1999");
	option_0.subElements[243]= pcData_268;
	HPcData pcData_269= new HPcData();
	pcData_269.setValue("\r\n");
	option_0.subElements[244]= pcData_269;
	HPcData pcData_270= new HPcData();
	pcData_270.setValue("\r\n");
	option_0.subElements[245]= pcData_270;
	HPcData pcData_271= new HPcData();
	pcData_271.setValue("\r\n");
	option_0.subElements[246]= pcData_271;
	HPcData pcData_272= new HPcData();
	pcData_272.setValue("Free Newsletters");
	option_0.subElements[247]= pcData_272;
	HPcData pcData_273= new HPcData();
	pcData_273.setValue("\r\n");
	option_0.subElements[248]= pcData_273;
	HPcData pcData_274= new HPcData();
	pcData_274.setValue("\r\n");
	option_0.subElements[249]= pcData_274;
	HPcData pcData_275= new HPcData();
	pcData_275.setValue("\r\n");
	option_0.subElements[250]= pcData_275;
	HPcData pcData_276= new HPcData();
	pcData_276.setValue("\r\n");
	option_0.subElements[251]= pcData_276;
	HPcData pcData_277= new HPcData();
	pcData_277.setValue("\r\n");
	option_0.subElements[252]= pcData_277;
	HPcData pcData_278= new HPcData();
	pcData_278.setValue("\r\n");
	option_0.subElements[253]= pcData_278;
	HPcData pcData_279= new HPcData();
	pcData_279.setValue("\r\n");
	option_0.subElements[254]= pcData_279;
	HPcData pcData_280= new HPcData();
	pcData_280.setValue("\r\n");
	option_0.subElements[255]= pcData_280;
	HPcData pcData_281= new HPcData();
	pcData_281.setValue("\r\n");
	option_0.subElements[256]= pcData_281;
	HPcData pcData_282= new HPcData();
	pcData_282.setValue("         \r\n");
	option_0.subElements[257]= pcData_282;
	HPcData pcData_283= new HPcData();
	pcData_283.setValue("   \r\n");
	option_0.subElements[258]= pcData_283;
	HPcData pcData_284= new HPcData();
	pcData_284.setValue("\r\n");
	option_0.subElements[259]= pcData_284;
	HPcData pcData_285= new HPcData();
	pcData_285.setValue("\r\n");
	option_0.subElements[260]= pcData_285;
	HPcData pcData_286= new HPcData();
	pcData_286.setValue("\r\n");
	option_0.subElements[261]= pcData_286;
	HPcData pcData_287= new HPcData();
	pcData_287.setValue("\r\n");
	option_0.subElements[262]= pcData_287;
	HPcData pcData_288= new HPcData();
	pcData_288.setValue("All Newsletters");
	option_0.subElements[263]= pcData_288;
	HPcData pcData_289= new HPcData();
	pcData_289.setValue("\r\n\r\n");
	option_0.subElements[264]= pcData_289;
	HPcData pcData_290= new HPcData();
	pcData_290.setValue("\r\n");
	option_0.subElements[265]= pcData_290;
	HPcData pcData_291= new HPcData();
	pcData_291.setValue("News Options:");
	option_0.subElements[266]= pcData_291;
	HPcData pcData_292= new HPcData();
	pcData_292.setValue("One Week View");
	option_0.subElements[267]= pcData_292;
	HPcData pcData_293= new HPcData();
	pcData_293.setValue("| ");
	option_0.subElements[268]= pcData_293;
	HPcData pcData_294= new HPcData();
	pcData_294.setValue("Send us your news tips");
	option_0.subElements[269]= pcData_294;
	HPcData pcData_295= new HPcData();
	pcData_295.setValue("| ");
	option_0.subElements[270]= pcData_295;
	HPcData pcData_296= new HPcData();
	pcData_296.setValue("Desktop News");
	option_0.subElements[271]= pcData_296;
	HPcData pcData_297= new HPcData();
	pcData_297.setValue("| ");
	option_0.subElements[272]= pcData_297;
	HPcData pcData_298= new HPcData();
	pcData_298.setValue(" ");
	option_0.subElements[273]= pcData_298;
	HPcData pcData_299= new HPcData();
	pcData_299.setValue("Advanced Search");
	option_0.subElements[274]= pcData_299;
	HPcData pcData_300= new HPcData();
	pcData_300.setValue("\r\n\r\n");
	option_0.subElements[275]= pcData_300;
	HPcData pcData_301= new HPcData();
	pcData_301.setValue("\r\n\r\n");
	option_0.subElements[276]= pcData_301;
	HComment comment_17= new HComment();
	comment_17.setValue(" Vignette StoryServer 4 Tue Dec 14 14:31:38 1999 --");
	option_0.subElements[277]= comment_17;
	HPcData pcData_302= new HPcData();
	pcData_302.setValue("\r\n\r\n\r\n");
	option_0.subElements[278]= pcData_302;
	HPcData pcData_303= new HPcData();
	pcData_303.setValue("\"Buy at Fujitsu PC Direct. Click Now!\"");
	option_0.subElements[279]= pcData_303;
	HPcData pcData_304= new HPcData();
	pcData_304.setValue("\r\n");
	option_0.subElements[280]= pcData_304;
	HPcData pcData_305= new HPcData();
	pcData_305.setValue("Contact us");
	option_0.subElements[281]= pcData_305;
	HPcData pcData_306= new HPcData();
	pcData_306.setValue("			");
	option_0.subElements[282]= pcData_306;
	HPcData pcData_307= new HPcData();
	pcData_307.setValue("\r\n			");
	option_0.subElements[283]= pcData_307;
	HPcData pcData_308= new HPcData();
	pcData_308.setValue("\r\n			");
	option_0.subElements[284]= pcData_308;
	HPcData pcData_309= new HPcData();
	pcData_309.setValue("\r\n");
	option_0.subElements[285]= pcData_309;
	HPcData pcData_310= new HPcData();
	pcData_310.setValue("\r\n			");
	option_0.subElements[286]= pcData_310;
	HPcData pcData_311= new HPcData();
	pcData_311.setValue("\r\n\r\n");
	option_0.subElements[287]= pcData_311;
	HPcData pcData_312= new HPcData();
	pcData_312.setValue(" ");
	option_0.subElements[288]= pcData_312;
	HPcData pcData_313= new HPcData();
	pcData_313.setValue("CNET Services:");
	option_0.subElements[289]= pcData_313;
	HPcData pcData_314= new HPcData();
	pcData_314.setValue(" ");
	option_0.subElements[290]= pcData_314;
	HPcData pcData_315= new HPcData();
	pcData_315.setValue("\r\n\r\n\r\n");
	option_0.subElements[291]= pcData_315;
	HPcData pcData_316= new HPcData();
	pcData_316.setValue("Stock");
	option_0.subElements[292]= pcData_316;
	HPcData pcData_317= new HPcData();
	pcData_317.setValue("Quotes");
	option_0.subElements[293]= pcData_317;
	HPcData pcData_318= new HPcData();
	pcData_318.setValue(" ");
	option_0.subElements[294]= pcData_318;
	HPcData pcData_319= new HPcData();
	pcData_319.setValue(" ");
	option_0.subElements[295]= pcData_319;
	HPcData pcData_320= new HPcData();
	pcData_320.setValue("Tech");
	option_0.subElements[296]= pcData_320;
	HPcData pcData_321= new HPcData();
	pcData_321.setValue("Auctions");
	option_0.subElements[297]= pcData_321;
	HPcData pcData_322= new HPcData();
	pcData_322.setValue(" ");
	option_0.subElements[298]= pcData_322;
	HPcData pcData_323= new HPcData();
	pcData_323.setValue(" ");
	option_0.subElements[299]= pcData_323;
	HPcData pcData_324= new HPcData();
	pcData_324.setValue("Tech");
	option_0.subElements[300]= pcData_324;
	HPcData pcData_325= new HPcData();
	pcData_325.setValue("News");
	option_0.subElements[301]= pcData_325;
	HPcData pcData_326= new HPcData();
	pcData_326.setValue(" ");
	option_0.subElements[302]= pcData_326;
	HPcData pcData_327= new HPcData();
	pcData_327.setValue(" ");
	option_0.subElements[303]= pcData_327;
	HPcData pcData_328= new HPcData();
	pcData_328.setValue("Free");
	option_0.subElements[304]= pcData_328;
	HPcData pcData_329= new HPcData();
	pcData_329.setValue("Downloads");
	option_0.subElements[305]= pcData_329;
	HPcData pcData_330= new HPcData();
	pcData_330.setValue(" ");
	option_0.subElements[306]= pcData_330;
	HPcData pcData_331= new HPcData();
	pcData_331.setValue(" ");
	option_0.subElements[307]= pcData_331;
	HPcData pcData_332= new HPcData();
	pcData_332.setValue("Search");
	option_0.subElements[308]= pcData_332;
	HPcData pcData_333= new HPcData();
	pcData_333.setValue(" ");
	option_0.subElements[309]= pcData_333;
	HPcData pcData_334= new HPcData();
	pcData_334.setValue(" ");
	option_0.subElements[310]= pcData_334;
	HPcData pcData_335= new HPcData();
	pcData_335.setValue("Games");
	option_0.subElements[311]= pcData_335;
	HPcData pcData_336= new HPcData();
	pcData_336.setValue(" ");
	option_0.subElements[312]= pcData_336;
	HPcData pcData_337= new HPcData();
	pcData_337.setValue(" ");
	option_0.subElements[313]= pcData_337;
	HPcData pcData_338= new HPcData();
	pcData_338.setValue("Latest");
	option_0.subElements[314]= pcData_338;
	HPcData pcData_339= new HPcData();
	pcData_339.setValue("PCs");
	option_0.subElements[315]= pcData_339;
	HPcData pcData_340= new HPcData();
	pcData_340.setValue(" ");
	option_0.subElements[316]= pcData_340;
	HPcData pcData_341= new HPcData();
	pcData_341.setValue(" ");
	option_0.subElements[317]= pcData_341;
	HPcData pcData_342= new HPcData();
	pcData_342.setValue("Business");
	option_0.subElements[318]= pcData_342;
	HPcData pcData_343= new HPcData();
	pcData_343.setValue("Solutions");
	option_0.subElements[319]= pcData_343;
	HPcData pcData_344= new HPcData();
	pcData_344.setValue(" ");
	option_0.subElements[320]= pcData_344;
	HPcData pcData_345= new HPcData();
	pcData_345.setValue(" ");
	option_0.subElements[321]= pcData_345;
	HPcData pcData_346= new HPcData();
	pcData_346.setValue("Hardware");
	option_0.subElements[322]= pcData_346;
	HPcData pcData_347= new HPcData();
	pcData_347.setValue("Buying");
	option_0.subElements[323]= pcData_347;
	HPcData pcData_348= new HPcData();
	pcData_348.setValue("Advice");
	option_0.subElements[324]= pcData_348;
	HPcData pcData_349= new HPcData();
	pcData_349.setValue(" ");
	option_0.subElements[325]= pcData_349;
	HPcData pcData_350= new HPcData();
	pcData_350.setValue(" ");
	option_0.subElements[326]= pcData_350;
	HPcData pcData_351= new HPcData();
	pcData_351.setValue("Find");
	option_0.subElements[327]= pcData_351;
	HPcData pcData_352= new HPcData();
	pcData_352.setValue("a");
	option_0.subElements[328]= pcData_352;
	HPcData pcData_353= new HPcData();
	pcData_353.setValue("Web");
	option_0.subElements[329]= pcData_353;
	HPcData pcData_354= new HPcData();
	pcData_354.setValue("Host");
	option_0.subElements[330]= pcData_354;
	HPcData pcData_355= new HPcData();
	pcData_355.setValue(" ");
	option_0.subElements[331]= pcData_355;
	HPcData pcData_356= new HPcData();
	pcData_356.setValue(" ");
	option_0.subElements[332]= pcData_356;
	HPcData pcData_357= new HPcData();
	pcData_357.setValue("Find");
	option_0.subElements[333]= pcData_357;
	HPcData pcData_358= new HPcData();
	pcData_358.setValue("an");
	option_0.subElements[334]= pcData_358;
	HPcData pcData_359= new HPcData();
	pcData_359.setValue("ISP");
	option_0.subElements[335]= pcData_359;
	HPcData pcData_360= new HPcData();
	pcData_360.setValue(" ");
	option_0.subElements[336]= pcData_360;
	HPcData pcData_361= new HPcData();
	pcData_361.setValue(" ");
	option_0.subElements[337]= pcData_361;
	HPcData pcData_362= new HPcData();
	pcData_362.setValue("Compare");
	option_0.subElements[338]= pcData_362;
	HPcData pcData_363= new HPcData();
	pcData_363.setValue("Prices");
	option_0.subElements[339]= pcData_363;
	HPcData pcData_364= new HPcData();
	pcData_364.setValue(" ");
	option_0.subElements[340]= pcData_364;
	HPcData pcData_365= new HPcData();
	pcData_365.setValue(" ");
	option_0.subElements[341]= pcData_365;
	HPcData pcData_366= new HPcData();
	pcData_366.setValue("Cool");
	option_0.subElements[342]= pcData_366;
	HPcData pcData_367= new HPcData();
	pcData_367.setValue("Toys");
	option_0.subElements[343]= pcData_367;
	HPcData pcData_368= new HPcData();
	pcData_368.setValue(" ");
	option_0.subElements[344]= pcData_368;
	HPcData pcData_369= new HPcData();
	pcData_369.setValue(" ");
	option_0.subElements[345]= pcData_369;
	HPcData pcData_370= new HPcData();
	pcData_370.setValue("Web");
	option_0.subElements[346]= pcData_370;
	HPcData pcData_371= new HPcData();
	pcData_371.setValue("Building");
	option_0.subElements[347]= pcData_371;
	HPcData pcData_372= new HPcData();
	pcData_372.setValue(" ");
	option_0.subElements[348]= pcData_372;
	HPcData pcData_373= new HPcData();
	pcData_373.setValue(" ");
	option_0.subElements[349]= pcData_373;
	HPcData pcData_374= new HPcData();
	pcData_374.setValue("Help");
	option_0.subElements[350]= pcData_374;
	HPcData pcData_375= new HPcData();
	pcData_375.setValue("&");
	option_0.subElements[351]= pcData_375;
	HPcData pcData_376= new HPcData();
	pcData_376.setValue("How-Tos");
	option_0.subElements[352]= pcData_376;
	HPcData pcData_377= new HPcData();
	pcData_377.setValue(" ");
	option_0.subElements[353]= pcData_377;
	HPcData pcData_378= new HPcData();
	pcData_378.setValue(" ");
	option_0.subElements[354]= pcData_378;
	HPcData pcData_379= new HPcData();
	pcData_379.setValue("Publish");
	option_0.subElements[355]= pcData_379;
	HPcData pcData_380= new HPcData();
	pcData_380.setValue("Your");
	option_0.subElements[356]= pcData_380;
	HPcData pcData_381= new HPcData();
	pcData_381.setValue("Opinion");
	option_0.subElements[357]= pcData_381;
	HPcData pcData_382= new HPcData();
	pcData_382.setValue(" ");
	option_0.subElements[358]= pcData_382;
	HPcData pcData_383= new HPcData();
	pcData_383.setValue(" ");
	option_0.subElements[359]= pcData_383;
	HPcData pcData_384= new HPcData();
	pcData_384.setValue("Build");
	option_0.subElements[360]= pcData_384;
	HPcData pcData_385= new HPcData();
	pcData_385.setValue("a");
	option_0.subElements[361]= pcData_385;
	HPcData pcData_386= new HPcData();
	pcData_386.setValue("Tech");
	option_0.subElements[362]= pcData_386;
	HPcData pcData_387= new HPcData();
	pcData_387.setValue("Store");
	option_0.subElements[363]= pcData_387;
	HPcData pcData_388= new HPcData();
	pcData_388.setValue(" ");
	option_0.subElements[364]= pcData_388;
	HPcData pcData_389= new HPcData();
	pcData_389.setValue(" ");
	option_0.subElements[365]= pcData_389;
	HPcData pcData_390= new HPcData();
	pcData_390.setValue("Tech");
	option_0.subElements[366]= pcData_390;
	HPcData pcData_391= new HPcData();
	pcData_391.setValue("Jobs");
	option_0.subElements[367]= pcData_391;
	HPcData pcData_392= new HPcData();
	pcData_392.setValue(" ");
	option_0.subElements[368]= pcData_392;
	HPcData pcData_393= new HPcData();
	pcData_393.setValue(" ");
	option_0.subElements[369]= pcData_393;
	HPcData pcData_394= new HPcData();
	pcData_394.setValue("Get");
	option_0.subElements[370]= pcData_394;
	HPcData pcData_395= new HPcData();
	pcData_395.setValue("a");
	option_0.subElements[371]= pcData_395;
	HPcData pcData_396= new HPcData();
	pcData_396.setValue("Job");
	option_0.subElements[372]= pcData_396;
	HPcData pcData_397= new HPcData();
	pcData_397.setValue("at");
	option_0.subElements[373]= pcData_397;
	HPcData pcData_398= new HPcData();
	pcData_398.setValue("CNET");
	option_0.subElements[374]= pcData_398;
	HPcData pcData_399= new HPcData();
	pcData_399.setValue(" ");
	option_0.subElements[375]= pcData_399;
	HPcData pcData_400= new HPcData();
	pcData_400.setValue(" ");
	option_0.subElements[376]= pcData_400;
	HPcData pcData_401= new HPcData();
	pcData_401.setValue("Join");
	option_0.subElements[377]= pcData_401;
	HPcData pcData_402= new HPcData();
	pcData_402.setValue("CNET's");
	option_0.subElements[378]= pcData_402;
	HPcData pcData_403= new HPcData();
	pcData_403.setValue("Affiliate");
	option_0.subElements[379]= pcData_403;
	HPcData pcData_404= new HPcData();
	pcData_404.setValue("Program");
	option_0.subElements[380]= pcData_404;
	HPcData pcData_405= new HPcData();
	pcData_405.setValue(" ");
	option_0.subElements[381]= pcData_405;
	HPcData pcData_406= new HPcData();
	pcData_406.setValue(" ");
	option_0.subElements[382]= pcData_406;
	HPcData pcData_407= new HPcData();
	pcData_407.setValue("Free");
	option_0.subElements[383]= pcData_407;
	HPcData pcData_408= new HPcData();
	pcData_408.setValue("Newsletters");
	option_0.subElements[384]= pcData_408;
	HPcData pcData_409= new HPcData();
	pcData_409.setValue(" ");
	option_0.subElements[385]= pcData_409;
	HPcData pcData_410= new HPcData();
	pcData_410.setValue(" 		\r\n	");
	option_0.subElements[386]= pcData_410;
	HPcData pcData_411= new HPcData();
	pcData_411.setValue("Free");
	option_0.subElements[387]= pcData_411;
	HPcData pcData_412= new HPcData();
	pcData_412.setValue("Email");
	option_0.subElements[388]= pcData_412;
	HPcData pcData_413= new HPcData();
	pcData_413.setValue("\r\n\r\n			");
	option_0.subElements[389]= pcData_413;
	HPcData pcData_414= new HPcData();
	pcData_414.setValue("\r\n			");
	option_0.subElements[390]= pcData_414;
	HPcData pcData_415= new HPcData();
	pcData_415.setValue("\r\n			");
	option_0.subElements[391]= pcData_415;
	HPcData pcData_416= new HPcData();
	pcData_416.setValue("\r\n			");
	option_0.subElements[392]= pcData_416;
	HPcData pcData_417= new HPcData();
	pcData_417.setValue("\r\n			");
	option_0.subElements[393]= pcData_417;
	HPcData pcData_418= new HPcData();
	pcData_418.setValue("\r\n			");
	option_0.subElements[394]= pcData_418;
	HPcData pcData_419= new HPcData();
	pcData_419.setValue("\r\n\r\n\r\n		");
	option_0.subElements[395]= pcData_419;
	HPcData pcData_420= new HPcData();
	pcData_420.setValue("\r\n		 ");
	option_0.subElements[396]= pcData_420;
	HPcData pcData_421= new HPcData();
	pcData_421.setValue("\r\n         ");
	option_0.subElements[397]= pcData_421;
	HPcData pcData_422= new HPcData();
	pcData_422.setValue("\r\n         ");
	option_0.subElements[398]= pcData_422;
	HPcData pcData_423= new HPcData();
	pcData_423.setValue("\r\n         ");
	option_0.subElements[399]= pcData_423;
	HPcData pcData_424= new HPcData();
	pcData_424.setValue("\r\n         ");
	option_0.subElements[400]= pcData_424;
	HPcData pcData_425= new HPcData();
	pcData_425.setValue("\r\n         ");
	option_0.subElements[401]= pcData_425;
	HPcData pcData_426= new HPcData();
	pcData_426.setValue("\r\n         ");
	option_0.subElements[402]= pcData_426;
	HPcData pcData_427= new HPcData();
	pcData_427.setValue("\r\n         ");
	option_0.subElements[403]= pcData_427;
	HPcData pcData_428= new HPcData();
	pcData_428.setValue("         \r\n         ");
	option_0.subElements[404]= pcData_428;
	HPcData pcData_429= new HPcData();
	pcData_429.setValue("   \r\n         ");
	option_0.subElements[405]= pcData_429;
	HPcData pcData_430= new HPcData();
	pcData_430.setValue("\r\n         ");
	option_0.subElements[406]= pcData_430;
	HPcData pcData_431= new HPcData();
	pcData_431.setValue("\r\n	\r\n		");
	option_0.subElements[407]= pcData_431;
	HPcData pcData_432= new HPcData();
	pcData_432.setValue("\r\n		");
	option_0.subElements[408]= pcData_432;
	HPcData pcData_433= new HPcData();
	pcData_433.setValue("\r\n		");
	option_0.subElements[409]= pcData_433;
	HPcData pcData_434= new HPcData();
	pcData_434.setValue("Free Newsletter!");
	option_0.subElements[410]= pcData_434;
	HPcData pcData_435= new HPcData();
	pcData_435.setValue("\r\n		");
	option_0.subElements[411]= pcData_435;
	HPcData pcData_436= new HPcData();
	pcData_436.setValue("\r\n		");
	option_0.subElements[412]= pcData_436;
	HPcData pcData_437= new HPcData();
	pcData_437.setValue("\r\n		");
	option_0.subElements[413]= pcData_437;
	HPcData pcData_438= new HPcData();
	pcData_438.setValue("\r\n		");
	option_0.subElements[414]= pcData_438;
	HPcData pcData_439= new HPcData();
	pcData_439.setValue("\r\n			\r\n			");
	option_0.subElements[415]= pcData_439;
	HPcData pcData_440= new HPcData();
	pcData_440.setValue("\r\n			");
	option_0.subElements[416]= pcData_440;
	HPcData pcData_441= new HPcData();
	pcData_441.setValue("\r\n			");
	option_0.subElements[417]= pcData_441;
	HPcData pcData_442= new HPcData();
	pcData_442.setValue("\r\n\r\n			");
	option_0.subElements[418]= pcData_442;
	HPcData pcData_443= new HPcData();
	pcData_443.setValue("\r\n			");
	option_0.subElements[419]= pcData_443;
	HPcData pcData_444= new HPcData();
	pcData_444.setValue("\r\n			");
	option_0.subElements[420]= pcData_444;
	HPcData pcData_445= new HPcData();
	pcData_445.setValue("\r\n\r\n");
	option_0.subElements[421]= pcData_445;
	HPcData pcData_446= new HPcData();
	pcData_446.setValue(" ");
	option_0.subElements[422]= pcData_446;
	HPcData pcData_447= new HPcData();
	pcData_447.setValue(" ");
	option_0.subElements[423]= pcData_447;
	HPcData pcData_448= new HPcData();
	pcData_448.setValue("\r\n\r\n");
	option_0.subElements[424]= pcData_448;
	HPcData pcData_449= new HPcData();
	pcData_449.setValue("Subscribe");
	option_0.subElements[425]= pcData_449;
	HPcData pcData_450= new HPcData();
	pcData_450.setValue("		  | \r\n");
	option_0.subElements[426]= pcData_450;
	HPcData pcData_451= new HPcData();
	pcData_451.setValue("How to advertise");
	option_0.subElements[427]= pcData_451;
	HPcData pcData_452= new HPcData();
	pcData_452.setValue("		  | \r\n");
	option_0.subElements[428]= pcData_452;
	HPcData pcData_453= new HPcData();
	pcData_453.setValue("Corrections");
	option_0.subElements[429]= pcData_453;
	HPcData pcData_454= new HPcData();
	pcData_454.setValue("		  | \r\n");
	option_0.subElements[430]= pcData_454;
	HPcData pcData_455= new HPcData();
	pcData_455.setValue("CNET Jobs");
	option_0.subElements[431]= pcData_455;
	HPcData pcData_456= new HPcData();
	pcData_456.setValue("		  | \r\n");
	option_0.subElements[432]= pcData_456;
	HPcData pcData_457= new HPcData();
	pcData_457.setValue("CNET Support");
	option_0.subElements[433]= pcData_457;
	HPcData pcData_458= new HPcData();
	pcData_458.setValue("		  | \r\n");
	option_0.subElements[434]= pcData_458;
	HPcData pcData_459= new HPcData();
	pcData_459.setValue("Message Boards");
	option_0.subElements[435]= pcData_459;
	HPcData pcData_460= new HPcData();
	pcData_460.setValue("\r\n					");
	option_0.subElements[436]= pcData_460;
	HPcData pcData_461= new HPcData();
	pcData_461.setValue("\r\n					");
	option_0.subElements[437]= pcData_461;
	HPcData pcData_462= new HPcData();
	pcData_462.setValue("\r\n");
	option_0.subElements[438]= pcData_462;
	HPcData pcData_463= new HPcData();
	pcData_463.setValue(" ");
	option_0.subElements[439]= pcData_463;
	HPcData pcData_464= new HPcData();
	pcData_464.setValue(" ");
	option_0.subElements[440]= pcData_464;
	HPcData pcData_465= new HPcData();
	pcData_465.setValue("\r\n\r\n");
	option_0.subElements[441]= pcData_465;
	HPcData pcData_466= new HPcData();
	pcData_466.setValue("About CNET");
	option_0.subElements[442]= pcData_466;
	HPcData pcData_467= new HPcData();
	pcData_467.setValue("\r\n		");
	option_0.subElements[443]= pcData_467;
	HPcData pcData_468= new HPcData();
	pcData_468.setValue("\r\n		");
	option_0.subElements[444]= pcData_468;
	HPcData pcData_469= new HPcData();
	pcData_469.setValue("\r\n		");
	option_0.subElements[445]= pcData_469;
	HPcData pcData_470= new HPcData();
	pcData_470.setValue("\r\n		\r\n	\r\n");
	option_0.subElements[446]= pcData_470;
	HPcData pcData_471= new HPcData();
	pcData_471.setValue("		\r\n");
	option_0.subElements[447]= pcData_471;
	HPcData pcData_472= new HPcData();
	pcData_472.setValue("\r\n");
	option_0.subElements[448]= pcData_472;
	HPcData pcData_473= new HPcData();
	pcData_473.setValue("Back to Top");
	option_0.subElements[449]= pcData_473;
	HPcData pcData_474= new HPcData();
	pcData_474.setValue("Join CNET, we're hiring");
	option_0.subElements[450]= pcData_474;
	HPcData pcData_475= new HPcData();
	pcData_475.setValue("\r\n\r\n");
	option_0.subElements[451]= pcData_475;
	HPcData pcData_476= new HPcData();
	pcData_476.setValue("\r\n\r\n");
	option_0.subElements[452]= pcData_476;
	HPcData pcData_477= new HPcData();
	pcData_477.setValue("\r\n\r\n");
	option_0.subElements[453]= pcData_477;
	HPcData pcData_478= new HPcData();
	pcData_478.setValue("Copyright");
	option_0.subElements[454]= pcData_478;
	HPcData pcData_479= new HPcData();
	pcData_479.setValue(" \r\n\r\n		");
	option_0.subElements[455]= pcData_479;
	HPcData pcData_480= new HPcData();
	pcData_480.setValue("1995-1999 CNET, Inc. All rights reserved. \r\n\r\n");
	option_0.subElements[456]= pcData_480;
	HPcData pcData_481= new HPcData();
	pcData_481.setValue("Privacy policy");
	option_0.subElements[457]= pcData_481;
	HPcData pcData_482= new HPcData();
	pcData_482.setValue(".");
	option_0.subElements[458]= pcData_482;
	HPcData pcData_483= new HPcData();
	pcData_483.setValue("\r\n\r\n");
	option_0.subElements[459]= pcData_483;
	HPcData pcData_484= new HPcData();
	pcData_484.setValue("\r\n");
	option_0.subElements[460]= pcData_484;
	HPcData pcData_485= new HPcData();
	pcData_485.setValue("\r\n	");
	option_0.subElements[461]= pcData_485;
	rootElement= html_0;
//	theDoc.serialize(args[args.length-1]);
return true;
    }
}
