/**************************************************
 File: Z000112_2.java.
 Desc: Automatic translation of HTML file Z000112_2.html.
 Date Translated: Fri Jan 14 09:47:37 2000.
**************************************************/


import wao.server.OutputStream;
import wao.html.*;


public class makeDoc_Z000112_2 extends HtmlDocCreation {

    static public void main() {
	HtmlDocCreation aTest= new makeDoc_Z000112_2();
	OutputStream aStream= new OutputStream();
	aTest.spitDoc(aStream);
    }

    public boolean createIt()
    {
	theDoc= new HtmlDoc("-//W3C//DTD HTML 3.2//EN");
	HHtml html_0= new HHtml();
	html_0.subElements= new HtmlElement[6];
	HPcData pcData_0= new HPcData();
	pcData_0.setValue("\r\n");
	html_0.subElements[0]= pcData_0;
	HHead head_0= new HHead();
	head_0.subElements= new HtmlElement[18];
	html_0.subElements[1]= head_0;
	HComment comment_0= new HComment();
	comment_0.setValue("PLS_META--");
	head_0.subElements[0]= comment_0;
	HMeta meta_0= new HMeta();
	meta_0.attributes= new HtmlAttribute[2];
	meta_0.attributes[0]= new HtmlAttribute("name", "\"NYT_HEADLINE\"");
	meta_0.attributes[1]= new HtmlAttribute("content", "\"In Europe, Media Companies Are Seeing Phones as the Future\"");
	head_0.subElements[1]= meta_0;
	HMeta meta_1= new HMeta();
	meta_1.attributes= new HtmlAttribute[2];
	meta_1.attributes[0]= new HtmlAttribute("name", "\"BY_LINE\"");
	meta_1.attributes[1]= new HtmlAttribute("content", "\"By  ERIC JENNER \"");
	head_0.subElements[2]= meta_1;
	HMeta meta_2= new HMeta();
	meta_2.attributes= new HtmlAttribute[2];
	meta_2.attributes[0]= new HtmlAttribute("name", "\"FIRSTPAR\"");
	meta_2.attributes[1]= new HtmlAttribute("content", "\"ROME -- Last week in Britain, following news of strong sales from the major mobile phone companies over the holiday shopping season, the news media reported that just slightly under 24 million \r\npeople in Britain one-fourth of the people in the country -- now own a mobile phone.\"");
	head_0.subElements[3]= meta_2;
	HMeta meta_3= new HMeta();
	meta_3.attributes= new HtmlAttribute[2];
	meta_3.attributes[0]= new HtmlAttribute("name", "\"DISPLAYDATE\"");
	meta_3.attributes[1]= new HtmlAttribute("content", "\"January 11, 2000\"");
	head_0.subElements[4]= meta_3;
	HMeta meta_4= new HMeta();
	meta_4.attributes= new HtmlAttribute[2];
	meta_4.attributes[0]= new HtmlAttribute("name", "\"NYT_SORTDATE\"");
	meta_4.attributes[1]= new HtmlAttribute("content", "\"20000111\"");
	meta_4.subElements= new HtmlElement[5];
	head_0.subElements[5]= meta_4;
	HComment comment_1= new HComment();
	comment_1.setValue(" 123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789 --");
	meta_4.subElements[0]= comment_1;
	HComment comment_2= new HComment();
	comment_2.setValue(" 123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789 --");
	meta_4.subElements[1]= comment_2;
	HComment comment_3= new HComment();
	comment_3.setValue(" 123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789 --");
	meta_4.subElements[2]= comment_3;
	HComment comment_4= new HComment();
	comment_4.setValue(" 123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789 --");
	meta_4.subElements[3]= comment_4;
	HComment comment_5= new HComment();
	comment_5.setValue("ELEMENT TITLE --");
	meta_4.subElements[4]= comment_5;
	HTitle title_0= new HTitle();
	title_0.subElements= new HtmlElement[1];
	head_0.subElements[6]= title_0;
	HPcData pcData_1= new HPcData();
	pcData_1.setValue("In Europe, Media Companies Are Seeing Phones as the Future");
	title_0.subElements[0]= pcData_1;
	HComment comment_6= new HComment();
	comment_6.setValue("ELEMENT META--");
	head_0.subElements[7]= comment_6;
	HMeta meta_5= new HMeta();
	meta_5.attributes= new HtmlAttribute[2];
	meta_5.attributes[0]= new HtmlAttribute("name", "\"Filingmethod\"");
	meta_5.attributes[1]= new HtmlAttribute("content", "\"Fetch (text file)\"");
	head_0.subElements[8]= meta_5;
	HMeta meta_6= new HMeta();
	meta_6.attributes= new HtmlAttribute[2];
	meta_6.attributes[0]= new HtmlAttribute("name", "\"UnixSlug \"");
	meta_6.attributes[1]= new HtmlAttribute("content", "\"../backfield/savekeep/12mobile.txt\"");
	head_0.subElements[9]= meta_6;
	HMeta meta_7= new HMeta();
	meta_7.attributes= new HtmlAttribute[1];
	meta_7.attributes[0]= new HtmlAttribute("name", "\"Date\"");
	head_0.subElements[10]= meta_7;
	HMeta meta_8= new HMeta();
	meta_8.attributes= new HtmlAttribute[1];
	meta_8.attributes[0]= new HtmlAttribute("name", "\"Type\"");
	head_0.subElements[11]= meta_8;
	HMeta meta_9= new HMeta();
	meta_9.attributes= new HtmlAttribute[1];
	meta_9.attributes[0]= new HtmlAttribute("name", "\"section\"");
	head_0.subElements[12]= meta_9;
	HMeta meta_10= new HMeta();
	meta_10.attributes= new HtmlAttribute[1];
	meta_10.attributes[0]= new HtmlAttribute("name", "\"wire\"");
	head_0.subElements[13]= meta_10;
	HMeta meta_11= new HMeta();
	meta_11.attributes= new HtmlAttribute[1];
	meta_11.attributes[0]= new HtmlAttribute("name", "\"subsection\"");
	head_0.subElements[14]= meta_11;
	HMeta meta_12= new HMeta();
	meta_12.attributes= new HtmlAttribute[1];
	meta_12.attributes[0]= new HtmlAttribute("name", "\"locale\"");
	head_0.subElements[15]= meta_12;
	HMeta meta_13= new HMeta();
	meta_13.attributes= new HtmlAttribute[1];
	meta_13.attributes[0]= new HtmlAttribute("name", "\"byline\"");
	head_0.subElements[16]= meta_13;
	HMeta meta_14= new HMeta();
	meta_14.attributes= new HtmlAttribute[1];
	meta_14.attributes[0]= new HtmlAttribute("name", "\"headline\"");
	head_0.subElements[17]= meta_14;
	HPcData pcData_2= new HPcData();
	pcData_2.setValue("\r\n");
	html_0.subElements[2]= pcData_2;
	HComment comment_7= new HComment();
	comment_7.setValue("plsfield:TEXT--");
	html_0.subElements[3]= comment_7;
	HPcData pcData_3= new HPcData();
	pcData_3.setValue("\r\n");
	html_0.subElements[4]= pcData_3;
	HBody body_0= new HBody();
	body_0.attributes= new HtmlAttribute[4];
	body_0.attributes[0]= new HtmlAttribute("bgcolor", "\"#ffffff\"");
	body_0.attributes[1]= new HtmlAttribute("vlink", "#444464");
	body_0.attributes[2]= new HtmlAttribute("link", "#000066");
	body_0.attributes[3]= new HtmlAttribute("background", "http://graphics.nytimes.com/images/back.c.gif");
	body_0.subElements= new HtmlElement[2];
	html_0.subElements[5]= body_0;
	HPcData pcData_4= new HPcData();
	pcData_4.setValue("\r\n\r\n");
	body_0.subElements[0]= pcData_4;
	HTable table_0= new HTable();
	table_0.attributes= new HtmlAttribute[3];
	table_0.attributes[0]= new HtmlAttribute("border", "0");
	table_0.attributes[1]= new HtmlAttribute("cellpadding", "0");
	table_0.attributes[2]= new HtmlAttribute("cellspacing", "0");
	table_0.subElements= new HtmlElement[1];
	body_0.subElements[1]= table_0;
	HTableRow tableRow_0= new HTableRow();
	tableRow_0.subElements= new HtmlElement[1];
	table_0.subElements[0]= tableRow_0;
	HTableData tableData_0= new HTableData();
	tableData_0.attributes= new HtmlAttribute[3];
	tableData_0.attributes[0]= new HtmlAttribute("align", "left");
	tableData_0.attributes[1]= new HtmlAttribute("width", "600");
	tableData_0.attributes[2]= new HtmlAttribute("valign", "top");
	tableData_0.subElements= new HtmlElement[7];
	tableRow_0.subElements[0]= tableData_0;
	HPcData pcData_5= new HPcData();
	pcData_5.setValue("\r\n");
	tableData_0.subElements[0]= pcData_5;
	HImg img_0= new HImg();
	img_0.attributes= new HtmlAttribute[4];
	img_0.attributes[0]= new HtmlAttribute("src", "\"http://graphics.nytimes.com/images/pixel.gif\"");
	img_0.attributes[1]= new HtmlAttribute("border", "0");
	img_0.attributes[2]= new HtmlAttribute("width", "600");
	img_0.attributes[3]= new HtmlAttribute("height", "1");
	tableData_0.subElements[1]= img_0;
	HPcData pcData_6= new HPcData();
	pcData_6.setValue("\r\n\r\n");
	tableData_0.subElements[2]= pcData_6;
	HTable table_1= new HTable();
	table_1.attributes= new HtmlAttribute[13];
	table_1.attributes[0]= new HtmlAttribute("border", "0");
	table_1.attributes[1]= new HtmlAttribute("cellpadding", "0");
	table_1.attributes[2]= new HtmlAttribute("cellspacing", "0");
	table_1.attributes[3]= new HtmlAttribute("align", "left");
	table_1.attributes[4]= new HtmlAttribute("width", "60");
	table_1.attributes[5]= new HtmlAttribute("align", "left");
	table_1.attributes[6]= new HtmlAttribute("width", "480");
	table_1.attributes[7]= new HtmlAttribute("border", "\"0\"");
	table_1.attributes[8]= new HtmlAttribute("width", "\"468\"");
	table_1.attributes[9]= new HtmlAttribute("border", "\"0\"");
	table_1.attributes[10]= new HtmlAttribute("width", "\"468\"");
	table_1.attributes[11]= new HtmlAttribute("border", "0");
	table_1.attributes[12]= new HtmlAttribute("width", "468");
	tableData_0.subElements[3]= table_1;
	HPcData pcData_7= new HPcData();
	pcData_7.setValue("\r\n\r\n");
	tableData_0.subElements[4]= pcData_7;
	HPcData pcData_8= new HPcData();
	pcData_8.setValue("\r\n");
	tableData_0.subElements[5]= pcData_8;
	HBlockQuote blockQuote_0= new HBlockQuote();
	blockQuote_0.subElements= new HtmlElement[1];
	tableData_0.subElements[6]= blockQuote_0;
	HBlockQuote blockQuote_1= new HBlockQuote();
	blockQuote_1.subElements= new HtmlElement[27];
	blockQuote_0.subElements[0]= blockQuote_1;
	HPcData pcData_9= new HPcData();
	pcData_9.setValue("\r\n");
	blockQuote_1.subElements[0]= pcData_9;
	HPcData pcData_10= new HPcData();
	pcData_10.setValue("\r\n");
	blockQuote_1.subElements[1]= pcData_10;
	HComment comment_8= new HComment();
	comment_8.setValue("DATE--");
	blockQuote_1.subElements[2]= comment_8;
	HPcData pcData_11= new HPcData();
	pcData_11.setValue("\r\n");
	blockQuote_1.subElements[3]= pcData_11;
	HPcData pcData_12= new HPcData();
	pcData_12.setValue("\r\n");
	blockQuote_1.subElements[4]= pcData_12;
	HHeading heading_0= new HHeading();
	heading_0.subElements= new HtmlElement[1];
	blockQuote_1.subElements[5]= heading_0;
	HPcData pcData_13= new HPcData();
	pcData_13.setValue("January 12, 2000");
	heading_0.subElements[0]= pcData_13;
	HBreak break_0= new HBreak();
	blockQuote_1.subElements[6]= break_0;
	HPcData pcData_14= new HPcData();
	pcData_14.setValue("\r\n");
	blockQuote_1.subElements[7]= pcData_14;
	HPcData pcData_15= new HPcData();
	pcData_15.setValue("\r\n");
	blockQuote_1.subElements[8]= pcData_15;
	HComment comment_9= new HComment();
	comment_9.setValue("HEADLINE--");
	blockQuote_1.subElements[9]= comment_9;
	HPcData pcData_16= new HPcData();
	pcData_16.setValue(" \r\n");
	blockQuote_1.subElements[10]= pcData_16;
	HPcData pcData_17= new HPcData();
	pcData_17.setValue("\r\n");
	blockQuote_1.subElements[11]= pcData_17;
	HHeading heading_0= new HHeading();
	heading_0.subElements= new HtmlElement[1];
	blockQuote_1.subElements[12]= heading_0;
	HPcData pcData_18= new HPcData();
	pcData_18.setValue("In Europe, Media Companies Are Seeing Phones as the Future");
	heading_0.subElements[0]= pcData_18;
	HPcData pcData_19= new HPcData();
	pcData_19.setValue("\r\n");
	blockQuote_1.subElements[13]= pcData_19;
	HPcData pcData_20= new HPcData();
	pcData_20.setValue("\r\n");
	blockQuote_1.subElements[14]= pcData_20;
	HComment comment_10= new HComment();
	comment_10.setValue("BYLINE--");
	blockQuote_1.subElements[15]= comment_10;
	HPcData pcData_21= new HPcData();
	pcData_21.setValue("\r\n");
	blockQuote_1.subElements[16]= pcData_21;
	HPcData pcData_22= new HPcData();
	pcData_22.setValue("\r\n");
	blockQuote_1.subElements[17]= pcData_22;
	HHeading heading_1= new HHeading();
	heading_1.subElements= new HtmlElement[1];
	blockQuote_1.subElements[18]= heading_1;
	HPcData pcData_23= new HPcData();
	pcData_23.setValue("By  ERIC JENNER ");
	heading_1.subElements[0]= pcData_23;
	HPcData pcData_24= new HPcData();
	pcData_24.setValue("\r\n");
	blockQuote_1.subElements[19]= pcData_24;
	HPcData pcData_25= new HPcData();
	pcData_25.setValue("\r\n");
	blockQuote_1.subElements[20]= pcData_25;
	HComment comment_11= new HComment();
	comment_11.setValue("TEXT--");
	blockQuote_1.subElements[21]= comment_11;
	HPcData pcData_26= new HPcData();
	pcData_26.setValue("\r\n");
	blockQuote_1.subElements[22]= pcData_26;
	HImg img_1= new HImg();
	img_1.attributes= new HtmlAttribute[6];
	img_1.attributes[0]= new HtmlAttribute("src", "\"/images/r.gif\"");
	img_1.attributes[1]= new HtmlAttribute("alt", "R");
	img_1.attributes[2]= new HtmlAttribute("align", "left");
	img_1.attributes[3]= new HtmlAttribute("border", "0");
	img_1.attributes[4]= new HtmlAttribute("height", "34");
	img_1.attributes[5]= new HtmlAttribute("width", "33");
	blockQuote_1.subElements[23]= img_1;
	HPcData pcData_27= new HPcData();
	pcData_27.setValue("OME -- Last week in Britain, following news of strong sales from the major mobile phone companies over the holiday shopping season, the news media reported that just slightly under 24 million people in Britain one-fourth of the people in the country -- now own a mobile phone.\r\n");
	blockQuote_1.subElements[24]= pcData_27;
	HPara para_0= new HPara();
	para_0.subElements= new HtmlElement[6];
	blockQuote_1.subElements[25]= para_0;
	HPcData pcData_28= new HPcData();
	pcData_28.setValue("\r\nBritons are just the latest to be taken with this one-time accouterment, now social and business necessity. According to ");
	para_0.subElements[0]= pcData_28;
	HAnchor anchor_0= new HAnchor();
	anchor_0.attributes= new HtmlAttribute[1];
	anchor_0.attributes[0]= new HtmlAttribute("href", "#1");
	anchor_0.subElements= new HtmlElement[1];
	para_0.subElements[1]= anchor_0;
	HPcData pcData_29= new HPcData();
	pcData_29.setValue("Forrester Research");
	anchor_0.subElements[0]= pcData_29;
	HPcData pcData_30= new HPcData();
	pcData_30.setValue(", a consulting company in Cambridge, Mass., half of the people in Italy own a cellular phone, while in Norway, Sweden and Finland ownership is even higher. Across Western Europe, more than one out of every three people totes a mobile phone. \r\n \r\n\r\n\r\n\r\n\r\n");
	para_0.subElements[2]= pcData_30;
	HBreak break_1= new HBreak();
	para_0.subElements[3]= break_1;
	HPcData pcData_31= new HPcData();
	pcData_31.setValue("\r\n");
	para_0.subElements[4]= pcData_31;
	HPcData pcData_32= new HPcData();
	pcData_32.setValue(" \r\n");
	para_0.subElements[5]= pcData_32;
	HTable table_2= new HTable();
	table_2.attributes= new HtmlAttribute[5];
	table_2.attributes[0]= new HtmlAttribute("align", "left");
	table_2.attributes[1]= new HtmlAttribute("border", "0");
	table_2.attributes[2]= new HtmlAttribute("width", "213");
	table_2.attributes[3]= new HtmlAttribute("cellpadding", "0");
	table_2.attributes[4]= new HtmlAttribute("cellspacing", "0");
	table_2.subElements= new HtmlElement[2];
	blockQuote_1.subElements[26]= table_2;
	HTableRow tableRow_1= new HTableRow();
	tableRow_1.subElements= new HtmlElement[2];
	table_2.subElements[0]= tableRow_1;
	HTableData tableData_1= new HTableData();
	tableData_1.attributes= new HtmlAttribute[3];
	tableData_1.attributes[0]= new HtmlAttribute("valign", "bottom");
	tableData_1.attributes[1]= new HtmlAttribute("height", "32");
	tableData_1.attributes[2]= new HtmlAttribute("width", "205");
	tableData_1.subElements= new HtmlElement[3];
	tableRow_1.subElements[0]= tableData_1;
	HPcData pcData_33= new HPcData();
	pcData_33.setValue(" ");
	tableData_1.subElements[0]= pcData_33;
	HHr hr_0= new HHr();
	hr_0.attributes= new HtmlAttribute[1];
	hr_0.attributes[0]= new HtmlAttribute("size", "1");
	tableData_1.subElements[1]= hr_0;
	HPcData pcData_34= new HPcData();
	pcData_34.setValue(" ");
	tableData_1.subElements[2]= pcData_34;
	HTableData tableData_2= new HTableData();
	tableData_2.attributes= new HtmlAttribute[2];
	tableData_2.attributes[0]= new HtmlAttribute("width", "8");
	tableData_2.attributes[1]= new HtmlAttribute("rowspan", "4");
	tableRow_1.subElements[1]= tableData_2;
	HTableRow tableRow_2= new HTableRow();
	tableRow_2.subElements= new HtmlElement[1];
	table_2.subElements[1]= tableRow_2;
	HTableData tableData_3= new HTableData();
	tableData_3.attributes= new HtmlAttribute[2];
	tableData_3.attributes[0]= new HtmlAttribute("align", "left");
	tableData_3.attributes[1]= new HtmlAttribute("width", "205");
	tableData_3.subElements= new HtmlElement[2];
	tableRow_2.subElements[0]= tableData_3;
	HPcData pcData_35= new HPcData();
	pcData_35.setValue(" ");
	tableData_3.subElements[0]= pcData_35;
	HFont font_0= new HFont();
	font_0.attributes= new HtmlAttribute[2];
	font_0.attributes[0]= new HtmlAttribute("color", "\"#ab0000\"");
	font_0.attributes[1]= new HtmlAttribute("size", "\"+2\"");
	font_0.subElements= new HtmlElement[53];
	tableData_3.subElements[1]= font_0;
	HPcData pcData_36= new HPcData();
	pcData_36.setValue(" \r\n");
	font_0.subElements[0]= pcData_36;
	HBold bold_0= new HBold();
	bold_0.subElements= new HtmlElement[90];
	font_0.subElements[1]= bold_0;
	HPcData pcData_37= new HPcData();
	pcData_37.setValue("“What's pretty clear is that the way in which people are consuming news is rapidly changing.”");
	bold_0.subElements[0]= pcData_37;
	HPcData pcData_38= new HPcData();
	pcData_38.setValue(" \r\n");
	bold_0.subElements[1]= pcData_38;
	HPcData pcData_39= new HPcData();
	pcData_39.setValue(" ");
	bold_0.subElements[2]= pcData_39;
	HPcData pcData_40= new HPcData();
	pcData_40.setValue(" ");
	bold_0.subElements[3]= pcData_40;
	HPcData pcData_41= new HPcData();
	pcData_41.setValue("\r\n");
	bold_0.subElements[4]= pcData_41;
	HPcData pcData_42= new HPcData();
	pcData_42.setValue(" ");
	bold_0.subElements[5]= pcData_42;
	HPcData pcData_43= new HPcData();
	pcData_43.setValue(" ");
	bold_0.subElements[6]= pcData_43;
	HFont font_1= new HFont();
	font_1.attributes= new HtmlAttribute[2];
	font_1.attributes[0]= new HtmlAttribute("size", "\"-1\"");
	font_1.attributes[1]= new HtmlAttribute("color", "000000");
	font_1.subElements= new HtmlElement[2];
	bold_0.subElements[7]= font_1;
	HPcData pcData_44= new HPcData();
	pcData_44.setValue("\r\n");
	font_1.subElements[0]= pcData_44;
	HBold bold_1= new HBold();
	bold_1.subElements= new HtmlElement[1];
	font_1.subElements[1]= bold_1;
	HPcData pcData_45= new HPcData();
	pcData_45.setValue("Neil Martinson, head of media relations, BBC");
	bold_1.subElements[0]= pcData_45;
	HPcData pcData_46= new HPcData();
	pcData_46.setValue(" ");
	bold_0.subElements[8]= pcData_46;
	HPcData pcData_47= new HPcData();
	pcData_47.setValue(" ");
	bold_0.subElements[9]= pcData_47;
	HPcData pcData_48= new HPcData();
	pcData_48.setValue(" ");
	bold_0.subElements[10]= pcData_48;
	HPcData pcData_49= new HPcData();
	pcData_49.setValue(" ");
	bold_0.subElements[11]= pcData_49;
	HPcData pcData_50= new HPcData();
	pcData_50.setValue(" ");
	bold_0.subElements[12]= pcData_50;
	HPcData pcData_51= new HPcData();
	pcData_51.setValue(" ");
	bold_0.subElements[13]= pcData_51;
	HPcData pcData_52= new HPcData();
	pcData_52.setValue(" ");
	bold_0.subElements[14]= pcData_52;
	HPcData pcData_53= new HPcData();
	pcData_53.setValue(" ");
	bold_0.subElements[15]= pcData_53;
	HPcData pcData_54= new HPcData();
	pcData_54.setValue(" ");
	bold_0.subElements[16]= pcData_54;
	HComment comment_12= new HComment();
	comment_12.setValue("@--");
	bold_0.subElements[17]= comment_12;
	HPcData pcData_55= new HPcData();
	pcData_55.setValue(" \r\n");
	bold_0.subElements[18]= pcData_55;
	HPcData pcData_56= new HPcData();
	pcData_56.setValue(" \r\n");
	bold_0.subElements[19]= pcData_56;
	HBreak break_2= new HBreak();
	bold_0.subElements[20]= break_2;
	HPcData pcData_57= new HPcData();
	pcData_57.setValue("\r\n\r\n");
	bold_0.subElements[21]= pcData_57;
	HPcData pcData_58= new HPcData();
	pcData_58.setValue("\r\nThis European zest for mobile communications has not escaped the notice of the media companies. In fact, the mobile phone is increasingly seen as a bridge between the converging worlds of traditional media and the Internet. The ubiquitous mobile phone, and other wireless devices for that matter, offers an obvious way to reach a broader European audience, especially when one considers the comparatively low numbers of Internet-connected PCs. \r\n");
	bold_0.subElements[22]= pcData_58;
	HPcData pcData_59= new HPcData();
	pcData_59.setValue("\r\n\"Take, for example, Italy, where there are five mobile phones for every computer that's connected to the Net,\" said Matthew Nordan, a senior analyst with Forrester. \"If you want to expand your market by moving beyond people who buy newspapers to people who use other communications media, the Web is probably not the right place to go to get lots and lots of them. But cell phones are a perfect one.\" \r\n");
	bold_0.subElements[23]= pcData_59;
	HPcData pcData_60= new HPcData();
	pcData_60.setValue("\r\nA Forrester report directed by Nordan found that 9 out of 10 Internet executives in Europe plan to launch Internet sites specifically for mobile devices. Nordan predicts that by 2004, 34 percent of Europeans will regularly use the Internet this way. \r\n");
	bold_0.subElements[24]= pcData_60;
	HPcData pcData_61= new HPcData();
	pcData_61.setValue("\r\nUpdates from news organizations have proven to be among the most popular of the wireless services, which can either function as an e-mail service, receiving news headlines and stock quotes, or can work more like a Web browser on a PC, reading special pared-down Internet sites. \r\n");
	bold_0.subElements[25]= pcData_61;
	HPcData pcData_62= new HPcData();
	pcData_62.setValue("\r\n\"News seems to be the big winner so far, based on evidence from Norway,\" said Lars Godell, an analyst with Forrester in Amsterdam who follows mobile developments in Scandinavia. \r\n");
	bold_0.subElements[26]= pcData_62;
	HPcData pcData_63= new HPcData();
	pcData_63.setValue("\r\n\"They have this data that already exists,\" Nordan said. \"With a little bit of programming effort, it can be trimmed down, sliced and diced and put onto a cell phone.\" \r\n");
	bold_0.subElements[27]= pcData_63;
	HPcData pcData_64= new HPcData();
	pcData_64.setValue("\r\nBut, it is also a big revenue opportunity for the media companies. \r\n");
	bold_0.subElements[28]= pcData_64;
	HPcData pcData_65= new HPcData();
	pcData_65.setValue("\r\n\"Because it's a pay-per-use service,\" Nordan said, \"content providers can actually make money off of their content directly without selling a subscription. Cell phones can give them micropayments for free, which for many media providers has been the holy grail of the Internet that's just never materialized.\" \r\n");
	bold_0.subElements[29]= pcData_65;
	HPcData pcData_66= new HPcData();
	pcData_66.setValue("\r\nIn places like Finland, where mobile phone use is high, this has already proven true in older wireless platforms. \r\n");
	bold_0.subElements[30]= pcData_66;
	HPcData pcData_67= new HPcData();
	pcData_67.setValue("\r\n\"I think it's a potentially very large new market for us,\" said Jonathan Baile, managing director of Reuters Wireless Services. \r\n");
	bold_0.subElements[31]= pcData_67;
	HPcData pcData_68= new HPcData();
	pcData_68.setValue("\r\nReuters, based in Britain, is the world's largest news and television agency that supplies news, graphics, video pictures and data to Web sites, print media and television around the world. \r\n");
	bold_0.subElements[32]= pcData_68;
	HPcData pcData_69= new HPcData();
	pcData_69.setValue("\r\n\"I think that in a very short number of years, more people will access Internet-based information on wireless devices than they do on wired,\" Baile said in a telephone interview from Reuters headquarters in London. \r\n");
	bold_0.subElements[33]= pcData_69;
	HPcData pcData_70= new HPcData();
	pcData_70.setValue("\r\n\"Our ultimate aim,\" Baile said, \"is for anyone, anywhere, anytime to get access to highly personalized information direct from Reuters.\" \r\n \r\n");
	bold_0.subElements[34]= pcData_70;
	HPcData pcData_71= new HPcData();
	pcData_71.setValue("\r\n");
	bold_0.subElements[35]= pcData_71;
	HPcData pcData_72= new HPcData();
	pcData_72.setValue("\r\n");
	bold_0.subElements[36]= pcData_72;
	HPcData pcData_73= new HPcData();
	pcData_73.setValue("\r\n");
	bold_0.subElements[37]= pcData_73;
	HPcData pcData_74= new HPcData();
	pcData_74.setValue("\r\n");
	bold_0.subElements[38]= pcData_74;
	HBreak break_3= new HBreak();
	bold_0.subElements[39]= break_3;
	HPcData pcData_75= new HPcData();
	pcData_75.setValue("\r\n");
	bold_0.subElements[40]= pcData_75;
	HPcData pcData_76= new HPcData();
	pcData_76.setValue("\r\n");
	bold_0.subElements[41]= pcData_76;
	HPcData pcData_77= new HPcData();
	pcData_77.setValue("\r\n");
	bold_0.subElements[42]= pcData_77;
	HFont font_2= new HFont();
	font_2.attributes= new HtmlAttribute[1];
	font_2.attributes[0]= new HtmlAttribute("size", "-1");
	font_2.subElements= new HtmlElement[9];
	bold_0.subElements[43]= font_2;
	HPcData pcData_78= new HPcData();
	pcData_78.setValue("\r\n");
	font_2.subElements[0]= pcData_78;
	HBold bold_2= new HBold();
	bold_2.subElements= new HtmlElement[1];
	font_2.subElements[1]= bold_2;
	HPcData pcData_79= new HPcData();
	pcData_79.setValue("Related Articles");
	bold_2.subElements[0]= pcData_79;
	HBreak break_4= new HBreak();
	font_2.subElements[2]= break_4;
	HPcData pcData_80= new HPcData();
	pcData_80.setValue("\r\n \r\n");
	font_2.subElements[3]= pcData_80;
	HAnchor anchor_1= new HAnchor();
	anchor_1.attributes= new HtmlAttribute[1];
	anchor_1.attributes[0]= new HtmlAttribute("href", "\"http://www.nytimes.com/library/tech/99/10/cyber/eurobytes/19eurobytes.html\"");
	anchor_1.subElements= new HtmlElement[1];
	font_2.subElements[4]= anchor_1;
	HPcData pcData_81= new HPcData();
	pcData_81.setValue("Mobile Data Is Set to Take Off, but Glitches Remain");
	anchor_1.subElements[0]= pcData_81;
	HPcData pcData_82= new HPcData();
	pcData_82.setValue("\r\n");
	font_2.subElements[5]= pcData_82;
	HBreak break_5= new HBreak();
	font_2.subElements[6]= break_5;
	HPcData pcData_83= new HPcData();
	pcData_83.setValue(" (October 19, 1999)\r\n");
	font_2.subElements[7]= pcData_83;
	HPcData pcData_84= new HPcData();
	pcData_84.setValue("\r\n");
	font_2.subElements[8]= pcData_84;
	HPcData pcData_85= new HPcData();
	pcData_85.setValue("\r\n");
	bold_0.subElements[44]= pcData_85;
	HPcData pcData_86= new HPcData();
	pcData_86.setValue("\r\n");
	bold_0.subElements[45]= pcData_86;
	HComment comment_13= new HComment();
	comment_13.setValue(" @ --");
	bold_0.subElements[46]= comment_13;
	HPcData pcData_87= new HPcData();
	pcData_87.setValue("\r\n");
	bold_0.subElements[47]= pcData_87;
	HPcData pcData_88= new HPcData();
	pcData_88.setValue("\r\n\"It's very important,\" said Neil Martinson, head of media relations for the BBC. \"If 40 percent of the U.K. population has mobile phones, it's not something we can ignore.\" \r\n");
	bold_0.subElements[48]= pcData_88;
	HPcData pcData_89= new HPcData();
	pcData_89.setValue("\r\nBBC, which is supported by a license fee paid by residents of Britain, offers news services in Britain and news throughout the world on radio, TV and the Internet. \r\n");
	bold_0.subElements[49]= pcData_89;
	HPcData pcData_90= new HPcData();
	pcData_90.setValue("\r\n\"What's pretty clear,\" Martinson said from BBC Television Center in London, \"is that the way in which people are consuming news is rapidly changing.\" \r\n");
	bold_0.subElements[50]= pcData_90;
	HPcData pcData_91= new HPcData();
	pcData_91.setValue("\r\nFor whatever reason, new social patterns, a shift in demographics, a longer work day or differing expectations, Martinson said that the audience has always changed the way it wants to get news. \r\n");
	bold_0.subElements[51]= pcData_91;
	HPcData pcData_92= new HPcData();
	pcData_92.setValue("\r\n\"Over a period of time, audiences to traditional news programs will decline,\" Martinson said. \"If you take TV news, people in the U.K. tended to make an appointment to view. They knew the news was on at 6 o'clock or 9 o'clock. Over the years, there's been a gradual decline in those audiences.\" \r\n");
	bold_0.subElements[52]= pcData_92;
	HPcData pcData_93= new HPcData();
	pcData_93.setValue("\r\n\"Mobile devices are clearly the logical next step in terms of insuring within the U.K. that people who pay the license fee to the BBC can get the BBC news when they want, wherever they are.\" \r\n");
	bold_0.subElements[53]= pcData_93;
	HPcData pcData_94= new HPcData();
	pcData_94.setValue("\r\nFor reasons of convenience or otherwise, Poligrafici Editoriale, publisher of three of Italy's leading regional papers, has reached a broader audience through the mobile phone. Marco Pratellesi, the online editor for La Nazione, il Resto del Carlino, il Giorno and Quotidiano, believes that they have reached first-time readers through their mobile phone news service. \r\n");
	bold_0.subElements[54]= pcData_94;
	HPcData pcData_95= new HPcData();
	pcData_95.setValue("\r\nPoligrafici Editoriale currently has 100,000 subscribers to their wireless news service, offered in conjunction with Telecom Mobile Italia. \r\n");
	bold_0.subElements[55]= pcData_95;
	HPcData pcData_96= new HPcData();
	pcData_96.setValue("\r\n\"We are planning to charge a little fee for the service later this year,\" Pratellesi said. \"Our hopes are for a large number of users and, maybe, income from advertising.\" \r\n");
	bold_0.subElements[56]= pcData_96;
	HPcData pcData_97= new HPcData();
	pcData_97.setValue("\r\nThere are still doubts as to what sort of information people will want to get on their mobile phone. Some remain skeptical that with a screen as small as five lines, people will want to read full-text articles. But others say devices like personal digital assistants, or PDA's, could complement mobile phones. \r\n");
	bold_0.subElements[57]= pcData_97;
	HPcData pcData_98= new HPcData();
	pcData_98.setValue("\r\nThe mobile phone is perfect for providing targeted information, Nordan said. \"For financial news this is absolutely critical.\" \r\n");
	bold_0.subElements[58]= pcData_98;
	HPcData pcData_99= new HPcData();
	pcData_99.setValue("\r\n\"It's an intimate personal device that lots of folks use,\" Nordan said. \"You can, by working with a mobile operator, have some specific information about each and every subscriber and very tightly personalize all the content and potentially ads or sponsorship that you bring to them.\" \r\n");
	bold_0.subElements[59]= pcData_99;
	HPcData pcData_100= new HPcData();
	pcData_100.setValue("\r\n\"Whatever it is,\" Baile said, \"it's going to be personalized.\" \r\n");
	bold_0.subElements[60]= pcData_100;
	HPcData pcData_101= new HPcData();
	pcData_101.setValue("\r\nAlthough the current wireless networks are limited in the rate of data transmission -- it is still far below the speed of the typical modem -- the next generation of wireless network, often called 3G, promises transfer speeds 60 times faster than today's modems. With these speeds, audio and video will be quite reasonable. Reuters and the BBC are both developing products with this in mind. \r\n");
	bold_0.subElements[61]= pcData_101;
	HPcData pcData_102= new HPcData();
	pcData_102.setValue("\r\nWhether this sort of service will be available to everyone, however, is still to be determined. These networks will be expensive to construct and analysts expect they will be limited to areas of dense population.\r\n");
	bold_0.subElements[62]= pcData_102;
	HPcData pcData_103= new HPcData();
	pcData_103.setValue("\r\n");
	bold_0.subElements[63]= pcData_103;
	HPcData pcData_104= new HPcData();
	pcData_104.setValue("\r\n");
	bold_0.subElements[64]= pcData_104;
	HAnchor anchor_2= new HAnchor();
	anchor_2.attributes= new HtmlAttribute[1];
	anchor_2.attributes[0]= new HtmlAttribute("name", "1");
	bold_0.subElements[65]= anchor_2;
	HPcData pcData_105= new HPcData();
	pcData_105.setValue("\r\n");
	bold_0.subElements[66]= pcData_105;
	HBold bold_3= new HBold();
	bold_3.subElements= new HtmlElement[1];
	bold_0.subElements[67]= bold_3;
	HPcData pcData_106= new HPcData();
	pcData_106.setValue("Related Sites");
	bold_3.subElements[0]= pcData_106;
	HBreak break_6= new HBreak();
	bold_0.subElements[68]= break_6;
	HPcData pcData_107= new HPcData();
	pcData_107.setValue("\r\n");
	bold_0.subElements[69]= pcData_107;
	HFont font_3= new HFont();
	font_3.attributes= new HtmlAttribute[1];
	font_3.attributes[0]= new HtmlAttribute("size", "-1");
	font_3.subElements= new HtmlElement[1];
	bold_0.subElements[70]= font_3;
	HPcData pcData_108= new HPcData();
	pcData_108.setValue("These sites are not part of The New York Times on the Web, and The Times has no control over their content or availability. ");
	font_3.subElements[0]= pcData_108;
	HPcData pcData_109= new HPcData();
	pcData_109.setValue("\r\n");
	bold_0.subElements[71]= pcData_109;
	HPcData pcData_110= new HPcData();
	pcData_110.setValue("\r\n ");
	bold_0.subElements[72]= pcData_110;
	HAnchor anchor_3= new HAnchor();
	anchor_3.attributes= new HtmlAttribute[1];
	anchor_3.attributes[0]= new HtmlAttribute("href", "\"http://www.forrester.com/\"");
	anchor_3.subElements= new HtmlElement[1];
	bold_0.subElements[73]= anchor_3;
	HPcData pcData_111= new HPcData();
	pcData_111.setValue("Forrester Research");
	anchor_3.subElements[0]= pcData_111;
	HPcData pcData_112= new HPcData();
	pcData_112.setValue("\r\n");
	bold_0.subElements[74]= pcData_112;
	HAnchor anchor_4= new HAnchor();
	anchor_4.attributes= new HtmlAttribute[1];
	anchor_4.attributes[0]= new HtmlAttribute("href", "\"http://www.bbc.co.uk\"");
	anchor_4.subElements= new HtmlElement[1];
	bold_0.subElements[75]= anchor_4;
	HPcData pcData_113= new HPcData();
	pcData_113.setValue("BBC");
	anchor_4.subElements[0]= pcData_113;
	HPcData pcData_114= new HPcData();
	pcData_114.setValue("\r\n");
	bold_0.subElements[76]= pcData_114;
	HAnchor anchor_5= new HAnchor();
	anchor_5.attributes= new HtmlAttribute[1];
	anchor_5.attributes[0]= new HtmlAttribute("href", "\"http://www.reuters.com\"");
	anchor_5.subElements= new HtmlElement[1];
	bold_0.subElements[77]= anchor_5;
	HPcData pcData_115= new HPcData();
	pcData_115.setValue("Reuters");
	anchor_5.subElements[0]= pcData_115;
	HPcData pcData_116= new HPcData();
	pcData_116.setValue("\r\n");
	bold_0.subElements[78]= pcData_116;
	HAnchor anchor_6= new HAnchor();
	anchor_6.attributes= new HtmlAttribute[1];
	anchor_6.attributes[0]= new HtmlAttribute("href", "\"http://www.quotidiano.net\"");
	anchor_6.subElements= new HtmlElement[1];
	bold_0.subElements[79]= anchor_6;
	HPcData pcData_117= new HPcData();
	pcData_117.setValue("Quotidiano");
	anchor_6.subElements[0]= pcData_117;
	HPcData pcData_118= new HPcData();
	pcData_118.setValue("    \r\n");
	bold_0.subElements[80]= pcData_118;
	HAnchor anchor_7= new HAnchor();
	anchor_7.attributes= new HtmlAttribute[1];
	anchor_7.attributes[0]= new HtmlAttribute("href", "\"http://www.lanazione.it\"");
	anchor_7.subElements= new HtmlElement[1];
	bold_0.subElements[81]= anchor_7;
	HPcData pcData_119= new HPcData();
	pcData_119.setValue("La Nazione");
	anchor_7.subElements[0]= pcData_119;
	HPcData pcData_120= new HPcData();
	pcData_120.setValue("\r\n");
	bold_0.subElements[82]= pcData_120;
	HAnchor anchor_8= new HAnchor();
	anchor_8.attributes= new HtmlAttribute[1];
	anchor_8.attributes[0]= new HtmlAttribute("href", "\"http://www.ilrestodelcarlino.it\"");
	anchor_8.subElements= new HtmlElement[1];
	bold_0.subElements[83]= anchor_8;
	HPcData pcData_121= new HPcData();
	pcData_121.setValue("il Resto del Carlino");
	anchor_8.subElements[0]= pcData_121;
	HPcData pcData_122= new HPcData();
	pcData_122.setValue("\r\n");
	bold_0.subElements[84]= pcData_122;
	HAnchor anchor_9= new HAnchor();
	anchor_9.attributes= new HtmlAttribute[1];
	anchor_9.attributes[0]= new HtmlAttribute("href", "\"http://www.ilgiorno.it\"");
	anchor_9.subElements= new HtmlElement[1];
	bold_0.subElements[85]= anchor_9;
	HPcData pcData_123= new HPcData();
	pcData_123.setValue("il Giorno");
	anchor_9.subElements[0]= pcData_123;
	HPcData pcData_124= new HPcData();
	pcData_124.setValue("\r\n");
	bold_0.subElements[86]= pcData_124;
	HPcData pcData_125= new HPcData();
	pcData_125.setValue("\r\n");
	bold_0.subElements[87]= pcData_125;
	HPcData pcData_126= new HPcData();
	pcData_126.setValue("\r\n");
	bold_0.subElements[88]= pcData_126;
	HPcData pcData_127= new HPcData();
	pcData_127.setValue("Additional link");
	bold_0.subElements[89]= pcData_127;
	HPcData pcData_128= new HPcData();
	pcData_128.setValue("\r\n  ");
	font_0.subElements[2]= pcData_128;
	HAnchor anchor_10= new HAnchor();
	anchor_10.attributes= new HtmlAttribute[1];
	anchor_10.attributes[0]= new HtmlAttribute("href", "\"http://www.gelon.net/\"");
	anchor_10.subElements= new HtmlElement[1];
	font_0.subElements[3]= anchor_10;
	HPcData pcData_129= new HPcData();
	pcData_129.setValue("Gelon.net");
	anchor_10.subElements[0]= pcData_129;
	HPcData pcData_130= new HPcData();
	pcData_130.setValue(" offers an emulator that illustrates the look of the new wireless Internet\r\n");
	font_0.subElements[4]= pcData_130;
	HPcData pcData_131= new HPcData();
	pcData_131.setValue("\r\n");
	font_0.subElements[5]= pcData_131;
	HPcData pcData_132= new HPcData();
	pcData_132.setValue("\r\n");
	font_0.subElements[6]= pcData_132;
	HPcData pcData_133= new HPcData();
	pcData_133.setValue("\r\n");
	font_0.subElements[7]= pcData_133;
	HComment comment_14= new HComment();
	comment_14.setValue("EMAIL FOR TRAVEL LOG--");
	font_0.subElements[8]= comment_14;
	HPcData pcData_134= new HPcData();
	pcData_134.setValue("\r\n");
	font_0.subElements[9]= pcData_134;
	HPcData pcData_135= new HPcData();
	pcData_135.setValue("\r\n");
	font_0.subElements[10]= pcData_135;
	HPcData pcData_136= new HPcData();
	pcData_136.setValue("\r\n");
	font_0.subElements[11]= pcData_136;
	HPcData pcData_137= new HPcData();
	pcData_137.setValue("Eric Jenner at ");
	font_0.subElements[12]= pcData_137;
	HAnchor anchor_11= new HAnchor();
	anchor_11.attributes= new HtmlAttribute[1];
	anchor_11.attributes[0]= new HtmlAttribute("href", "\"mailto:jenner@nytimes.com\"");
	anchor_11.subElements= new HtmlElement[1];
	font_0.subElements[13]= anchor_11;
	HPcData pcData_138= new HPcData();
	pcData_138.setValue("Jenner@nytimes.com");
	anchor_11.subElements[0]= pcData_138;
	HPcData pcData_139= new HPcData();
	pcData_139.setValue(" welcomes\r\nyour comments and suggestions.");
	font_0.subElements[14]= pcData_139;
	HPcData pcData_140= new HPcData();
	pcData_140.setValue("\r\n");
	font_0.subElements[15]= pcData_140;
	HPcData pcData_141= new HPcData();
	pcData_141.setValue("\r\n");
	font_0.subElements[16]= pcData_141;
	HPcData pcData_142= new HPcData();
	pcData_142.setValue("\r\n");
	font_0.subElements[17]= pcData_142;
	HComment comment_15= new HComment();
	comment_15.setValue(" @ --");
	font_0.subElements[18]= comment_15;
	HPcData pcData_143= new HPcData();
	pcData_143.setValue("\r\n");
	font_0.subElements[19]= pcData_143;
	HPcData pcData_144= new HPcData();
	pcData_144.setValue("\r\n");
	font_0.subElements[20]= pcData_144;
	HComment comment_16= new HComment();
	comment_16.setValue("plsfield:NYT_FOOTER--");
	font_0.subElements[21]= comment_16;
	HPcData pcData_145= new HPcData();
	pcData_145.setValue("\r\n");
	font_0.subElements[22]= pcData_145;
	HPcData pcData_146= new HPcData();
	pcData_146.setValue("\r\n");
	font_0.subElements[23]= pcData_146;
	HPcData pcData_147= new HPcData();
	pcData_147.setValue("\r\n");
	font_0.subElements[24]= pcData_147;
	HBreak break_7= new HBreak();
	font_0.subElements[25]= break_7;
	HPcData pcData_148= new HPcData();
	pcData_148.setValue("\r\n");
	font_0.subElements[26]= pcData_148;
	HPcData pcData_149= new HPcData();
	pcData_149.setValue("\r\n");
	font_0.subElements[27]= pcData_149;
	HBreak break_8= new HBreak();
	font_0.subElements[28]= break_8;
	HPcData pcData_150= new HPcData();
	pcData_150.setValue("\r\n");
	font_0.subElements[29]= pcData_150;
	HPcData pcData_151= new HPcData();
	pcData_151.setValue("\r\n ");
	font_0.subElements[30]= pcData_151;
	HPcData pcData_152= new HPcData();
	pcData_152.setValue("\r\n\r\n");
	font_0.subElements[31]= pcData_152;
	HAnchor anchor_12= new HAnchor();
	anchor_12.attributes= new HtmlAttribute[2];
	anchor_12.attributes[0]= new HtmlAttribute("href", "\"http://images3.nytimes.com/RealMedia/ads/click_lx.ads/www.nytimes.com/library/tech/00/01/cyber/articles/12mobile.html/0/Bottom/avonbk01/AVN1-3TAL.gif/61613031323232353338376433383730\"");
	anchor_12.attributes[1]= new HtmlAttribute("target", "\"_top\"");
	anchor_12.subElements= new HtmlElement[1];
	font_0.subElements[32]= anchor_12;
	HImg img_2= new HImg();
	img_2.attributes= new HtmlAttribute[5];
	img_2.attributes[0]= new HtmlAttribute("src", "\"http://images3.nytimes.com/RealMedia/ads/adstream_lx.ads/www.nytimes.com/library/tech/00/01/cyber/articles/12mobile.html/0/Bottom/avonbk01/AVN1-3TAL.gif/61613031323232353338376433383730\"");
	img_2.attributes[1]= new HtmlAttribute("border", "0");
	img_2.attributes[2]= new HtmlAttribute("width", "468");
	img_2.attributes[3]= new HtmlAttribute("height", "60");
	img_2.attributes[4]= new HtmlAttribute("alt", "\"Click here\"");
	anchor_12.subElements[0]= img_2;
	HPcData pcData_153= new HPcData();
	pcData_153.setValue("\r\n\r\n");
	font_0.subElements[33]= pcData_153;
	HPcData pcData_154= new HPcData();
	pcData_154.setValue("\r\n");
	font_0.subElements[34]= pcData_154;
	HPcData pcData_155= new HPcData();
	pcData_155.setValue("\r\n");
	font_0.subElements[35]= pcData_155;
	HPcData pcData_156= new HPcData();
	pcData_156.setValue("\r\n");
	font_0.subElements[36]= pcData_156;
	HFont font_4= new HFont();
	font_4.attributes= new HtmlAttribute[1];
	font_4.attributes[0]= new HtmlAttribute("size", "-1");
	font_4.subElements= new HtmlElement[67];
	font_0.subElements[37]= font_4;
	HPcData pcData_157= new HPcData();
	pcData_157.setValue("\r\n");
	font_4.subElements[0]= pcData_157;
	HPcData pcData_158= new HPcData();
	pcData_158.setValue("\r\n");
	font_4.subElements[1]= pcData_158;
	HAnchor anchor_13= new HAnchor();
	anchor_13.attributes= new HtmlAttribute[1];
	anchor_13.attributes[0]= new HtmlAttribute("href", "\"/\"");
	anchor_13.subElements= new HtmlElement[1];
	font_4.subElements[2]= anchor_13;
	HBold bold_4= new HBold();
	bold_4.subElements= new HtmlElement[1];
	anchor_13.subElements[0]= bold_4;
	HPcData pcData_159= new HPcData();
	pcData_159.setValue("Home");
	bold_4.subElements[0]= pcData_159;
	HPcData pcData_160= new HPcData();
	pcData_160.setValue(" | \r\n");
	font_4.subElements[3]= pcData_160;
	HAnchor anchor_14= new HAnchor();
	anchor_14.attributes= new HtmlAttribute[1];
	anchor_14.attributes[0]= new HtmlAttribute("href", "\"/info/contents/siteindex.html\"");
	anchor_14.subElements= new HtmlElement[1];
	font_4.subElements[4]= anchor_14;
	HBold bold_5= new HBold();
	bold_5.subElements= new HtmlElement[1];
	anchor_14.subElements[0]= bold_5;
	HPcData pcData_161= new HPcData();
	pcData_161.setValue("Site Index");
	bold_5.subElements[0]= pcData_161;
	HPcData pcData_162= new HPcData();
	pcData_162.setValue(" | \r\n");
	font_4.subElements[5]= pcData_162;
	HAnchor anchor_15= new HAnchor();
	anchor_15.attributes= new HtmlAttribute[1];
	anchor_15.attributes[0]= new HtmlAttribute("href", "\"/search/daily/\"");
	anchor_15.subElements= new HtmlElement[1];
	font_4.subElements[6]= anchor_15;
	HBold bold_6= new HBold();
	bold_6.subElements= new HtmlElement[1];
	anchor_15.subElements[0]= bold_6;
	HPcData pcData_163= new HPcData();
	pcData_163.setValue("Site Search");
	bold_6.subElements[0]= pcData_163;
	HPcData pcData_164= new HPcData();
	pcData_164.setValue("  | \r\n");
	font_4.subElements[7]= pcData_164;
	HAnchor anchor_16= new HAnchor();
	anchor_16.attributes= new HtmlAttribute[1];
	anchor_16.attributes[0]= new HtmlAttribute("href", "\"/comment/\"");
	anchor_16.subElements= new HtmlElement[1];
	font_4.subElements[8]= anchor_16;
	HBold bold_7= new HBold();
	bold_7.subElements= new HtmlElement[1];
	anchor_16.subElements[0]= bold_7;
	HPcData pcData_165= new HPcData();
	pcData_165.setValue("Forums");
	bold_7.subElements[0]= pcData_165;
	HPcData pcData_166= new HPcData();
	pcData_166.setValue("  | \r\n");
	font_4.subElements[9]= pcData_166;
	HAnchor anchor_17= new HAnchor();
	anchor_17.attributes= new HtmlAttribute[1];
	anchor_17.attributes[0]= new HtmlAttribute("href", "\"/archives/\"");
	anchor_17.subElements= new HtmlElement[1];
	font_4.subElements[10]= anchor_17;
	HBold bold_8= new HBold();
	bold_8.subElements= new HtmlElement[1];
	anchor_17.subElements[0]= bold_8;
	HPcData pcData_167= new HPcData();
	pcData_167.setValue("Archives");
	bold_8.subElements[0]= pcData_167;
	HPcData pcData_168= new HPcData();
	pcData_168.setValue(" | \r\n");
	font_4.subElements[11]= pcData_168;
	HAnchor anchor_18= new HAnchor();
	anchor_18.attributes= new HtmlAttribute[1];
	anchor_18.attributes[0]= new HtmlAttribute("href", "\"/marketplace/\"");
	anchor_18.subElements= new HtmlElement[1];
	font_4.subElements[12]= anchor_18;
	HBold bold_9= new HBold();
	bold_9.subElements= new HtmlElement[1];
	anchor_18.subElements[0]= bold_9;
	HPcData pcData_169= new HPcData();
	pcData_169.setValue("Marketplace");
	bold_9.subElements[0]= pcData_169;
	HPcData pcData_170= new HPcData();
	pcData_170.setValue("\r\n");
	font_4.subElements[13]= pcData_170;
	HPcData pcData_171= new HPcData();
	pcData_171.setValue("\r\n");
	font_4.subElements[14]= pcData_171;
	HAnchor anchor_19= new HAnchor();
	anchor_19.attributes= new HtmlAttribute[1];
	anchor_19.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/late/\"");
	anchor_19.subElements= new HtmlElement[1];
	font_4.subElements[15]= anchor_19;
	HPcData pcData_172= new HPcData();
	pcData_172.setValue("Quick News");
	anchor_19.subElements[0]= pcData_172;
	HPcData pcData_173= new HPcData();
	pcData_173.setValue("  | \r\n");
	font_4.subElements[16]= pcData_173;
	HAnchor anchor_20= new HAnchor();
	anchor_20.attributes= new HtmlAttribute[1];
	anchor_20.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/front/\"");
	anchor_20.subElements= new HtmlElement[1];
	font_4.subElements[17]= anchor_20;
	HPcData pcData_174= new HPcData();
	pcData_174.setValue("Page One Plus");
	anchor_20.subElements[0]= pcData_174;
	HPcData pcData_175= new HPcData();
	pcData_175.setValue("  | \r\n");
	font_4.subElements[18]= pcData_175;
	HAnchor anchor_21= new HAnchor();
	anchor_21.attributes= new HtmlAttribute[1];
	anchor_21.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/world/\"");
	anchor_21.subElements= new HtmlElement[1];
	font_4.subElements[19]= anchor_21;
	HPcData pcData_176= new HPcData();
	pcData_176.setValue("International");
	anchor_21.subElements[0]= pcData_176;
	HPcData pcData_177= new HPcData();
	pcData_177.setValue("  | \r\n");
	font_4.subElements[20]= pcData_177;
	HAnchor anchor_22= new HAnchor();
	anchor_22.attributes= new HtmlAttribute[1];
	anchor_22.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/national/\"");
	anchor_22.subElements= new HtmlElement[1];
	font_4.subElements[21]= anchor_22;
	HPcData pcData_178= new HPcData();
	pcData_178.setValue("National/N.Y.");
	anchor_22.subElements[0]= pcData_178;
	HPcData pcData_179= new HPcData();
	pcData_179.setValue("   | \r\n");
	font_4.subElements[22]= pcData_179;
	HAnchor anchor_23= new HAnchor();
	anchor_23.attributes= new HtmlAttribute[1];
	anchor_23.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/business/\"");
	anchor_23.subElements= new HtmlElement[1];
	font_4.subElements[23]= anchor_23;
	HPcData pcData_180= new HPcData();
	pcData_180.setValue("Business");
	anchor_23.subElements[0]= pcData_180;
	HPcData pcData_181= new HPcData();
	pcData_181.setValue("   | \r\n");
	font_4.subElements[24]= pcData_181;
	HAnchor anchor_24= new HAnchor();
	anchor_24.attributes= new HtmlAttribute[1];
	anchor_24.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/tech/\"");
	anchor_24.subElements= new HtmlElement[1];
	font_4.subElements[25]= anchor_24;
	HPcData pcData_182= new HPcData();
	pcData_182.setValue("Technology");
	anchor_24.subElements[0]= pcData_182;
	HPcData pcData_183= new HPcData();
	pcData_183.setValue("  | \r\n");
	font_4.subElements[26]= pcData_183;
	HAnchor anchor_25= new HAnchor();
	anchor_25.attributes= new HtmlAttribute[1];
	anchor_25.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/science/\"");
	anchor_25.subElements= new HtmlElement[1];
	font_4.subElements[27]= anchor_25;
	HPcData pcData_184= new HPcData();
	pcData_184.setValue("Science");
	anchor_25.subElements[0]= pcData_184;
	HPcData pcData_185= new HPcData();
	pcData_185.setValue("   | \r\n");
	font_4.subElements[28]= pcData_185;
	HAnchor anchor_26= new HAnchor();
	anchor_26.attributes= new HtmlAttribute[1];
	anchor_26.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/sports/\"");
	anchor_26.subElements= new HtmlElement[1];
	font_4.subElements[29]= anchor_26;
	HPcData pcData_186= new HPcData();
	pcData_186.setValue("Sports");
	anchor_26.subElements[0]= pcData_186;
	HPcData pcData_187= new HPcData();
	pcData_187.setValue("   | \r\n");
	font_4.subElements[30]= pcData_187;
	HAnchor anchor_27= new HAnchor();
	anchor_27.attributes= new HtmlAttribute[1];
	anchor_27.attributes[0]= new HtmlAttribute("href", "\"/weather/\"");
	anchor_27.subElements= new HtmlElement[1];
	font_4.subElements[31]= anchor_27;
	HPcData pcData_188= new HPcData();
	pcData_188.setValue("Weather");
	anchor_27.subElements[0]= pcData_188;
	HPcData pcData_189= new HPcData();
	pcData_189.setValue("  | \r\n");
	font_4.subElements[32]= pcData_189;
	HAnchor anchor_28= new HAnchor();
	anchor_28.attributes= new HtmlAttribute[1];
	anchor_28.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/editorial/\"");
	anchor_28.subElements= new HtmlElement[1];
	font_4.subElements[33]= anchor_28;
	HPcData pcData_190= new HPcData();
	pcData_190.setValue("Editorial");
	anchor_28.subElements[0]= pcData_190;
	HPcData pcData_191= new HPcData();
	pcData_191.setValue("    | \r\n");
	font_4.subElements[34]= pcData_191;
	HAnchor anchor_29= new HAnchor();
	anchor_29.attributes= new HtmlAttribute[1];
	anchor_29.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/oped/\"");
	anchor_29.subElements= new HtmlElement[1];
	font_4.subElements[35]= anchor_29;
	HPcData pcData_192= new HPcData();
	pcData_192.setValue("Op-Ed");
	anchor_29.subElements[0]= pcData_192;
	HPcData pcData_193= new HPcData();
	pcData_193.setValue(" | \r\n");
	font_4.subElements[36]= pcData_193;
	HAnchor anchor_30= new HAnchor();
	anchor_30.attributes= new HtmlAttribute[1];
	anchor_30.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/artleisure/\"");
	anchor_30.subElements= new HtmlElement[1];
	font_4.subElements[37]= anchor_30;
	HPcData pcData_194= new HPcData();
	pcData_194.setValue("Arts");
	anchor_30.subElements[0]= pcData_194;
	HPcData pcData_195= new HPcData();
	pcData_195.setValue("   | \r\n");
	font_4.subElements[38]= pcData_195;
	HAnchor anchor_31= new HAnchor();
	anchor_31.attributes= new HtmlAttribute[1];
	anchor_31.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/auto/\"");
	anchor_31.subElements= new HtmlElement[1];
	font_4.subElements[39]= anchor_31;
	HPcData pcData_196= new HPcData();
	pcData_196.setValue("Automobiles");
	anchor_31.subElements[0]= pcData_196;
	HPcData pcData_197= new HPcData();
	pcData_197.setValue("   | \r\n");
	font_4.subElements[40]= pcData_197;
	HAnchor anchor_32= new HAnchor();
	anchor_32.attributes= new HtmlAttribute[1];
	anchor_32.attributes[0]= new HtmlAttribute("href", "\"/books/yr/mo/day/home/\"");
	anchor_32.subElements= new HtmlElement[1];
	font_4.subElements[41]= anchor_32;
	HPcData pcData_198= new HPcData();
	pcData_198.setValue("Books");
	anchor_32.subElements[0]= pcData_198;
	HPcData pcData_199= new HPcData();
	pcData_199.setValue("  | \r\n");
	font_4.subElements[42]= pcData_199;
	HAnchor anchor_33= new HAnchor();
	anchor_33.attributes= new HtmlAttribute[1];
	anchor_33.attributes[0]= new HtmlAttribute("href", "\"/diversions/\"");
	anchor_33.subElements= new HtmlElement[1];
	font_4.subElements[43]= anchor_33;
	HPcData pcData_200= new HPcData();
	pcData_200.setValue("Diversions");
	anchor_33.subElements[0]= pcData_200;
	HPcData pcData_201= new HPcData();
	pcData_201.setValue("   | \r\n");
	font_4.subElements[44]= pcData_201;
	HAnchor anchor_34= new HAnchor();
	anchor_34.attributes= new HtmlAttribute[1];
	anchor_34.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/jobmarket/\"");
	anchor_34.subElements= new HtmlElement[1];
	font_4.subElements[45]= anchor_34;
	HPcData pcData_202= new HPcData();
	pcData_202.setValue("Job Market");
	anchor_34.subElements[0]= pcData_202;
	HPcData pcData_203= new HPcData();
	pcData_203.setValue("   | \r\n");
	font_4.subElements[46]= pcData_203;
	HAnchor anchor_35= new HAnchor();
	anchor_35.attributes= new HtmlAttribute[1];
	anchor_35.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/realestate/\"");
	anchor_35.subElements= new HtmlElement[1];
	font_4.subElements[47]= anchor_35;
	HPcData pcData_204= new HPcData();
	pcData_204.setValue("Real Estate");
	anchor_35.subElements[0]= pcData_204;
	HPcData pcData_205= new HPcData();
	pcData_205.setValue("  | \r\n");
	font_4.subElements[48]= pcData_205;
	HAnchor anchor_36= new HAnchor();
	anchor_36.attributes= new HtmlAttribute[1];
	anchor_36.attributes[0]= new HtmlAttribute("href", "\"/yr/mo/day/travel/\"");
	anchor_36.subElements= new HtmlElement[1];
	font_4.subElements[49]= anchor_36;
	HPcData pcData_206= new HPcData();
	pcData_206.setValue("Travel");
	anchor_36.subElements[0]= pcData_206;
	HPcData pcData_207= new HPcData();
	pcData_207.setValue(" \r\n");
	font_4.subElements[50]= pcData_207;
	HPcData pcData_208= new HPcData();
	pcData_208.setValue("\r\n");
	font_4.subElements[51]= pcData_208;
	HAnchor anchor_37= new HAnchor();
	anchor_37.attributes= new HtmlAttribute[1];
	anchor_37.attributes[0]= new HtmlAttribute("href", "\"/subscribe/help/\"");
	anchor_37.subElements= new HtmlElement[1];
	font_4.subElements[52]= anchor_37;
	HPcData pcData_209= new HPcData();
	pcData_209.setValue("Help/Feedback");
	anchor_37.subElements[0]= pcData_209;
	HPcData pcData_210= new HPcData();
	pcData_210.setValue("  | \r\n");
	font_4.subElements[53]= pcData_210;
	HAnchor anchor_38= new HAnchor();
	anchor_38.attributes= new HtmlAttribute[1];
	anchor_38.attributes[0]= new HtmlAttribute("href", "\"/classified/\"");
	anchor_38.subElements= new HtmlElement[1];
	font_4.subElements[54]= anchor_38;
	HPcData pcData_211= new HPcData();
	pcData_211.setValue("Classifieds");
	anchor_38.subElements[0]= pcData_211;
	HPcData pcData_212= new HPcData();
	pcData_212.setValue("   | \r\n");
	font_4.subElements[55]= pcData_212;
	HAnchor anchor_39= new HAnchor();
	anchor_39.attributes= new HtmlAttribute[1];
	anchor_39.attributes[0]= new HtmlAttribute("href", "\"/info/contents/services.html\"");
	anchor_39.subElements= new HtmlElement[1];
	font_4.subElements[56]= anchor_39;
	HPcData pcData_213= new HPcData();
	pcData_213.setValue("Services");
	anchor_39.subElements[0]= pcData_213;
	HPcData pcData_214= new HPcData();
	pcData_214.setValue("   | \r\n");
	font_4.subElements[57]= pcData_214;
	HAnchor anchor_40= new HAnchor();
	anchor_40.attributes= new HtmlAttribute[1];
	anchor_40.attributes[0]= new HtmlAttribute("href", "\"http://www.nytoday.com\"");
	anchor_40.subElements= new HtmlElement[1];
	font_4.subElements[58]= anchor_40;
	HPcData pcData_215= new HPcData();
	pcData_215.setValue("New York Today");
	anchor_40.subElements[0]= pcData_215;
	HPcData pcData_216= new HPcData();
	pcData_216.setValue(" \r\n\r\n");
	font_4.subElements[59]= pcData_216;
	HPcData pcData_217= new HPcData();
	pcData_217.setValue("\r\n");
	font_4.subElements[60]= pcData_217;
	HPcData pcData_218= new HPcData();
	pcData_218.setValue("\r\n");
	font_4.subElements[61]= pcData_218;
	HPcData pcData_219= new HPcData();
	pcData_219.setValue("\r\n");
	font_4.subElements[62]= pcData_219;
	HAnchor anchor_41= new HAnchor();
	anchor_41.attributes= new HtmlAttribute[1];
	anchor_41.attributes[0]= new HtmlAttribute("href", "\"/subscribe/help/copyright.html\"");
	anchor_41.subElements= new HtmlElement[1];
	font_4.subElements[63]= anchor_41;
	HBold bold_10= new HBold();
	bold_10.subElements= new HtmlElement[1];
	anchor_41.subElements[0]= bold_10;
	HPcData pcData_220= new HPcData();
	pcData_220.setValue("Copyright 2000 The New York Times Company");
	bold_10.subElements[0]= pcData_220;
	HPcData pcData_221= new HPcData();
	pcData_221.setValue("\r\n");
	font_4.subElements[64]= pcData_221;
	HPcData pcData_222= new HPcData();
	pcData_222.setValue("\r\n\r\n");
	font_4.subElements[65]= pcData_222;
	HPcData pcData_223= new HPcData();
	pcData_223.setValue("\r\n");
	font_4.subElements[66]= pcData_223;
	HPcData pcData_224= new HPcData();
	pcData_224.setValue("\r\n");
	font_0.subElements[38]= pcData_224;
	HPcData pcData_225= new HPcData();
	pcData_225.setValue("\r\n");
	font_0.subElements[39]= pcData_225;
	HPcData pcData_226= new HPcData();
	pcData_226.setValue("\r\n");
	font_0.subElements[40]= pcData_226;
	HPcData pcData_227= new HPcData();
	pcData_227.setValue("\r\n");
	font_0.subElements[41]= pcData_227;
	HImg img_3= new HImg();
	img_3.attributes= new HtmlAttribute[4];
	img_3.attributes[0]= new HtmlAttribute("src", "\"http://graphics.nytimes.com/images/pixel.gif\"");
	img_3.attributes[1]= new HtmlAttribute("border", "0");
	img_3.attributes[2]= new HtmlAttribute("width", "14");
	img_3.attributes[3]= new HtmlAttribute("height", "1");
	font_0.subElements[42]= img_3;
	HPcData pcData_228= new HPcData();
	pcData_228.setValue("\r\n");
	font_0.subElements[43]= pcData_228;
	HPcData pcData_229= new HPcData();
	pcData_229.setValue("\r\n");
	font_0.subElements[44]= pcData_229;
	HImg img_4= new HImg();
	img_4.attributes= new HtmlAttribute[4];
	img_4.attributes[0]= new HtmlAttribute("src", "\"http://graphics.nytimes.com/images/pixel.gif\"");
	img_4.attributes[1]= new HtmlAttribute("border", "0");
	img_4.attributes[2]= new HtmlAttribute("width", "140");
	img_4.attributes[3]= new HtmlAttribute("height", "2");
	font_0.subElements[45]= img_4;
	HPcData pcData_230= new HPcData();
	pcData_230.setValue("\r\n\r\n");
	font_0.subElements[46]= pcData_230;
	HAnchor anchor_42= new HAnchor();
	anchor_42.attributes= new HtmlAttribute[2];
	anchor_42.attributes[0]= new HtmlAttribute("href", "\"http://images3.nytimes.com/RealMedia/ads/click_lx.ads/www.nytimes.com/library/tech/00/01/cyber/articles/12mobile.html/0/Right3/dgdash02/dig3-rtsd.gif/61613031323232353338376433383730\"");
	anchor_42.attributes[1]= new HtmlAttribute("target", "\"_top\"");
	anchor_42.subElements= new HtmlElement[1];
	font_0.subElements[47]= anchor_42;
	HImg img_5= new HImg();
	img_5.attributes= new HtmlAttribute[3];
	img_5.attributes[0]= new HtmlAttribute("src", "\"http://images3.nytimes.com/RealMedia/ads/adstream_lx.ads/www.nytimes.com/library/tech/00/01/cyber/articles/12mobile.html/0/Right3/dgdash02/dig3-rtsd.gif/61613031323232353338376433383730\"");
	img_5.attributes[1]= new HtmlAttribute("border", "0");
	img_5.attributes[2]= new HtmlAttribute("alt", "\"Click here.\"");
	anchor_42.subElements[0]= img_5;
	HPcData pcData_231= new HPcData();
	pcData_231.setValue("\r\n\r\n\r\n");
	font_0.subElements[48]= pcData_231;
	HPcData pcData_232= new HPcData();
	pcData_232.setValue("\r\n\r\n");
	font_0.subElements[49]= pcData_232;
	HPcData pcData_233= new HPcData();
	pcData_233.setValue("\r\n\r\n");
	font_0.subElements[50]= pcData_233;
	HPcData pcData_234= new HPcData();
	pcData_234.setValue("\r\n");
	font_0.subElements[51]= pcData_234;
	HPcData pcData_235= new HPcData();
	pcData_235.setValue("\r\n\r\n\r\n\r\n\r\n");
	font_0.subElements[52]= pcData_235;
	rootElement= html_0;
//	theDoc.serialize(args[args.length-1]);
return true;
    }
}
